### PR TITLE
fix kongingress CRD openAPIV3Schema validation error

### PR DESCRIPTION
**Pull request by ccfishk**
**What this PR does / why we need it**:
fix kongingress CRD openapiv3schema validation error

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

https://github.com/Kong/kubernetes-ingress-controller/issues/1807

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

**Review by mflendrich — CHANGES_REQUESTED** [review]
`deploy/single-v2/*` files are autogenerated using the `hack/deploy/build-single-manifests.sh` script. Changing files under `deploy/single*` directly is not the right way - you need to change the source file instead, and regenerate `deploy/single*` only then.

@shaneutt: how does this interact with #1763?

**Comment by ccfishk** [comment]
Good catch. Switching to source.

**Comment by ccfishk** [comment]
> `deploy/single-v2/*` files are autogenerated using the `hack/deploy/build-single-manifests.sh` script. Changing files under `deploy/single*` directly is not the right way - you need to change the source file instead, and regenerate `deploy/single*` only then.
> 
> @shaneutt: how does this interact with #1763?

I have been thinking parity cleans up only, the invalid found in this PR breaks deployment, regard this as a bug (https://github.com/Kong/kubernetes-ingress-controller/issues/1807)

**Comment by ccfishk** [comment]
> `deploy/single-v2/*` files are autogenerated using the `hack/deploy/build-single-manifests.sh` script. Changing files under `deploy/single*` directly is not the right way - you need to change the source file instead, and regenerate `deploy/single*` only then.
changed a1191e2a10cdb9cbd6ce66fd651bce5927b9a9b2
> 
> @shaneutt: how does this interact with #1763?

**Review by shaneutt — APPROVED** [review]
These changes look right, let's just make sure to do some manual testing and then :+1: 

@mflendrich It looks like Jimin changed the implementation and is now only targeting the extra CRD under base (which I've come to understand is manually managed and used for ee), we need your re-review on this as well just to double check this looks right to you too please :bow:

**Review by mflendrich — DISMISSED** [review]

**Comment by mflendrich** [comment]
This can't go in yet because the autogeneration consistency check (in the _lint_ CI job) complains. @ccfishk

**Comment by ccfishk** [comment]
This fix was covered by previous merged PR. close as it is.

**Pull request closed without merging**
