### PR TITLE
[Backport release/2.10.x] Backport #4238 to 2.10.x

### PR DESCRIPTION
**Pull request by randmonkey**
** Original PR info *** 
* fix: do not prepend ~ before regex paths for Kong < 3.0

* add tests for translating grpcroute

* add CHANGELOG

(cherry picked from commit 1b59a9bbeedeace8a1d3f800ec26681493b2fa6d)

**What this PR does / why we need it**:

manual backport of fixing translator of `GRPCRoute` #4238  to 2.10.x.
fixed conflicts on `CHANGELOG.md` .

**Which issue this PR fixes**:

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

**Review by pmalek — COMMENTED** [review]
> REVIEW: Do we need to add the CHANGELOG entry in this PR?

We can do it straight away here so that we don't forget what was cherry picked.

Also Please adjust the PR title to contain the original message + a prefix `[Backport release/2.10.x]`

**Comment by randmonkey** [comment]
> > REVIEW: Do we need to add the CHANGELOG entry in this PR?
> 
> We can do it straight away here so that we don't forget what was cherry picked.
> 
> Also Please adjust the PR title to contain the original message + a prefix `[Backport release/2.10.x]`

Updated the CHANGELOG.

**Comment by pmalek** [comment]
Please update the PR description (see: "REVIEW" comment which is not relevant anymore)

**Comment by randmonkey** [comment]
> Please update the PR description (see: "REVIEW" comment which is not relevant anymore)

done.

**Review by pmalek — APPROVED** [review]

**Pull request merged**
