### PR TITLE
chore(deps): bump ktf

### PR DESCRIPTION
**Pull request by czeslavo**
**What this PR does / why we need it**:

Fixes E2E tests that use Gateway API's kustomize manifests to deploy GW API's CRDs (https://github.com/Kong/kubernetes-ingress-controller/actions/runs/5571797159/jobs/10177200861). 

Workflow run as a proof for this fix working: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/5623274304

### CODE REVIEW

**Review by rainest — COMMENTED** [review]
Should this not be a change in KTF? It seems like we should instead modify [the kustomize apply functions](https://github.com/Kong/kubernetes-testing-framework/blob/df7ea3757e96774c9f4b43659c1b4dc589253987/pkg/clusters/utils.go#L211-L243) to use [kubectlWithArgs](https://github.com/Kong/kubernetes-testing-framework/blob/df7ea3757e96774c9f4b43659c1b4dc589253987/pkg/clusters/utils.go#L299-L319) (which generates a temp config and uses it) similar to [other apply functions](https://github.com/Kong/kubernetes-testing-framework/blob/df7ea3757e96774c9f4b43659c1b4dc589253987/pkg/clusters/utils.go#L260-L263)

**Comment by pmalek** [comment]
Do you mind adding a link to a commit that brings in the fix that we want here?

**Comment by pmalek** [comment]
BTW: with https://github.com/Kong/kubernetes-testing-framework/pull/754/files merged we can already rely on v0.33 being bumped by dependabot yes?

**Comment by czeslavo** [comment]
> BTW: with https://github.com/Kong/kubernetes-testing-framework/pull/754/files merged we can already rely on v0.33 being bumped by dependabot yes?

Yeah, I think so. I close this PR and we'll wait for the dependabot kick-in when v0.33.0 gets released. 👍

**Pull request closed without merging**
