### PR TITLE
chore(ci): don't run e2e in GKE clusters

### PR DESCRIPTION
**Pull request by czeslavo**
**What this PR does / why we need it**:

Due to the issues with running E2E tests on GKE we have (https://github.com/Kong/kubernetes-ingress-controller/issues/3331), we decided to switch all the tests to Kind for now, until we find a working solution for the problems described in the mentioned issue.

Issue for tracking the enablement of GKE E2E tests back once the problems are figured out: https://github.com/Kong/kubernetes-ingress-controller/issues/3348

**Which issue this PR fixes**:

Workaround for https://github.com/Kong/kubernetes-ingress-controller/issues/3331.

### CODE REVIEW

**Comment by pmalek** [comment]
Can you run e2e on this branch and kink it here? I am sceptical about this working on kind 1.26

**Comment by czeslavo** [comment]
> Can you run e2e on this branch and kink it here? I am sceptical about this working on kind 1.26

It's still running: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3874399771/jobs/6605545199. Why are you skeptical about that? Did we have issues with Kind v1.26.0 in the past?

**Comment by pmalek** [comment]
> > Can you run e2e on this branch and kink it here? I am sceptical about this working on kind 1.26
> 
> It's still running: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3874399771/jobs/6605545199. Why are you skeptical about that? Did we have issues with Kind v1.26.0 in the past?

Nope, I tried running kind with 1.26 last week and it didn't manage to deploy the cluster successfully.

BTW: this 

> It's still running: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3874399771/jobs/6605545199.

Is running e2e **targeted** which is a different workflow than what you're changing ( e2e and release) 😬 . (My opinion on this is unnecessarily complicated and we should extract the common parts out and parametrize those workflows - as I believe you suggested already at some point @czeslavo )

**Comment by czeslavo** [comment]
@pmalek as you suggested I've removed v1.26 tests for now as there's still no official Kind release for this k8s version. It's mentioned in https://github.com/Kong/kubernetes-ingress-controller/issues/3348 that using Kind v1.26 may be the solution as well.

**Review by pmalek — APPROVED** [review]

**Pull request merged**
