### PR TITLE
chore: namespace RBACs added

### PR DESCRIPTION
**Pull request by mlavacca**
The RBACs have been updated with grants to watch, list, and get namespaces.

**What this PR does / why we need it**:

The `*Route` controllers need to get namespaces [here](https://github.com/Kong/kubernetes-ingress-controller/blob/8003ef9cc3c1d2f53e00cca24d2f0949a505041e/internal/controllers/gateway/route_utils.go#L444).

**Which issue this PR fixes**:

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

**Comment by pmalek** [comment]
Does that mean that *Route never work with `NamespacesFromSelector` up until now?

**Comment by mlavacca** [comment]
> Does that mean that *Route never work with `NamespacesFromSelector` up until now?
It looks so. In that context, the controller starts spamming a "cannot list namespaces" error forever.

**Comment by programmer04** [comment]
Do we have any tests in place that try to catch such bugs?

**Comment by mlavacca** [comment]
Nope, we have no test with that selector among our test cases. That's why it silently failed. I think this should be tested upstream as well, I'll create a conformance test issue in the Gateway API repo about it.

**Review by rainest — APPROVED** [review]

**Pull request merged**
