### PR TITLE
test: update certs for TestHTTPSIngress

### LINKED ISSUE #4257: Update certificates used in integration tests
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

The integration test `TestHTTPSIngress` fails in running validation tests against Kong gateway image `kong/kong-gateway-dev:2.8.4.2-rc1`. After deep dive into the case, we found that the certificates used in the test case is problematic. The certificate having CN `foo.com` has an empty SAN field and is used for hostname `bar.example.com`. 

### Proposed Solution

- Update the certificate used in `TestHTTPSIngress`
- use the same hostname as in the certificate

### Additional information

_No response_

### Acceptance Criteria

_No response_

### PR DESCRIPTION
**Pull request by randmonkey**
**What this PR does / why we need it**:

The certificates in `tlsPairs` used in test cases `TestHTTPSIngress` and `TestTCPIngressTLSPassthrough` are expired, and the SANs inside does not match the hostname we used. This causes TLS failure against kong gateway image `kong/kong-gateway-dev:2.8.4.2-rc1`. To prevent the failures, we generated new certificates, and moved them into a single file.

**Which issue this PR fixes**:

fixes #4257 

**Special notes for your reviewer**:

 In this PR, we generated new certificates with the following settings:
`tlsPairFooExample`:
```
[ req ]
default_bits = 2048
prompt = no
default_md = sha256
req_extensions = req_ext
distinguished_name = dn

[ dn ]
C = US
ST = California
L = San Fransisco
O = Kong Inc
OU = team kubernetes
CN = foo.example

[ req_ext ]
subjectAltName = @alt_names

[ alt_names ]
DNS.1 = foo.example
```

`tlsPairBarExample`:
```
[ req ]
default_bits = 2048
prompt = no
default_md = sha256
req_extensions = req_ext
distinguished_name = dn

[ dn ]
C = US
ST = California
L = San Fransisco
O = Kong Inc
OU = team kubernetes
CN = bar.example

[ req_ext ]
subjectAltName = @alt_names

[ alt_names ]
DNS.1 = bar.example
```

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

**Comment by programmer04** [comment]
There is issue #4118 for unifying dealing with certificates in tests, you can see in it that in our tests in one place certificates are created for each run

**Comment by randmonkey** [comment]
> There is issue #4118 for unifying dealing with certificates in tests, you can see in it that in our tests in one place certificates are created for each run

@programmer04 So the suggested solution is to extract the `generateSelfSignedCert` function in #4058 into a general helper function?

**Comment by programmer04** [comment]
I think it would be nice to have just one implementation for all tests. I saw that you're touching this code, so I linked the issue to spread awareness. Generating certs on the fly ensures that nothing unexpected is encoded in the cert blob, you have knobs to configure it. WDYT?

**Comment by pmalek** [comment]
> I think it would be nice to have just one implementation for all tests.

+1

**Comment by randmonkey** [comment]
close this because we have #4271.

**Pull request closed without merging**
