### PR TITLE
Move internal/ to pkg/

### PR DESCRIPTION
**Pull request by SergeRadinovich**
Moves internal/ pkgs to pkg/ so that those pkgs can be imported by other projects

### CODE REVIEW

**Comment by hbagdi** [comment]
The packages in `internal` have been intentional up to this point.
We did have plans to move these out in future but doing this now is also okay. Thanks for the PR.

However, if you can move out only the `apis` and `client` package, we can accept this PR.
Other packages should remain inside the `internal` package.

**Comment by SergeRadinovich** [comment]
Have updated the PR - let me know if anything else is needed. Thanks

**Comment by hbagdi** [comment]
As per conventions, we should move `pkg/apis` to root-level `apis` package; `client` can live inside `pkg`.

Thoughts?

**Comment by hbagdi** [comment]
Also, please take a look at the failing lint jobs.

**Comment by SergeRadinovich** [comment]
> As per conventions, we should move `pkg/apis` to root-level `apis` package; `client` can live inside `pkg`.

I tend to follow these conventions: https://github.com/golang-standards/project-layout

which states:
`Don't put a lot of code in the application directory. If you think the code can be imported and used in other projects, then it should live in the /pkg directory`

So I would expect pkg/apis and pkg/client

> Also, please take a look at the failing lint jobs.

Will take a look cheers

**Comment by SergeRadinovich** [comment]
Regarding the lint errors - I am unsure why these aren't a problem before my changes. Is it possible that linter does not bother checking for stuttering in internal/? It is only picking up on the stutters after moving code to pkg/.

`pkg/client/configuration/clientset/versioned/typed/configuration/v1beta1/fake/fake_configuration_client.go:27:6: type name will be used as fake.FakeConfigurationV1beta1 by other packages, and that stutters; consider calling this ConfigurationV1beta1 (golint)
type FakeConfigurationV1beta1 struct {`

**Comment by hbagdi** [comment]
You want to add `pkg/apis` to https://github.com/Kong/kubernetes-ingress-controller/blob/master/.golangci.yml#L4

**Comment by SergeRadinovich** [comment]
Please have a look at the second commit regarding the linter fixes I had to make following your instructions: https://github.com/Kong/kubernetes-ingress-controller/pull/726/commits/0999138001d100b8016662730f8deaa0acb39869

**Comment by hbagdi** [comment]
Please sign the CLA.

**Comment by SergeRadinovich** [comment]
done, thanks

**Pull request merged**
