### PR TITLE
[wip][chore] Simplify sync configuration to proxy; Improve controller ingress configuration efficiency

### PR DESCRIPTION
**Pull request by ccfishk**
**What this PR does / why we need it**:
  Every cycle, proxy cache read all synced objects and process (proxy.KongUpdater) as it is - calculate checksum to detect newly added objects, compose deck interface, post config to admin api, proxy persists ingress configuration etc. 
  And, most of  the accumulated objects ingress data has been processed in previous cycle(s) - proxy already has the ingress entry, this mechanism introduced redundancy/repeated function call,  confusion. And it is bottleneck if the accumulated ingress becomes a large number.
  This PR introduce a light-weight memory cache - redis, work as ingress filter, controller only communicate newly added ingress (or, not processed ingress) to deck proxy.
   
 #1538 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

 remove unneded process.

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR
- []  no regression for either integration tests or unit tests.
- [ ]  able to deploy as many ingresses as the resource support.

### CODE REVIEW

**Review by rainest — CHANGES_REQUESTED** [review]
At minimum, this needs to account for the [custom entity blob's contents](https://github.com/Kong/kubernetes-ingress-controller/blob/next/pkg/deckgen/deckgen.go#L27-L29). Hashing `targetContent` only means that the controller won't reconfigure Kong when a user changes custom entities only. Probably easiest to do that by creating a temporary struct containing both `targetContent` and the custom entities blob and running `hashstructure.Hash()` on that.

**Questions on the hash strategy**

Can you show a small example how the change here clears the issue, e.g. a `targetContent` where hashing the `file.Content` version (what this change does) results in a consistent hash, but hashing the `json.Marshal(targetContent)` of the same `targetContent` does not? Is this something where you could add a regression unit test?

It seems like the advantage of hashstructure is that we'd be able to make use of the SlicesAsSets option, so that if we generate Kong routes `{routeA, routeB}` in one parser build and `{routeB, routeA}` on another we do not update config, because that order doesn't actually matter (the set of Kong routes is indeed a set in the maths sense), it's just an artifact of how Go loops work when building slices from a range. However, we don't use that option here.

I wouldn't expect `json.Marshal()` to permute the order of objects in its input as both Go slices and JSON arrays _do_ care about order, so it should preserve that: if you generate the same `targetContent` twice and marshal it, you get the same JSON blob. Thus it seems like this change without the ignore slice order option wouldn't change the end result--if we generate `targetContent`s with the same items in different orders (an issue that definitely has affected us in the past), we still wind up with different hashes with this proposed change.

Not sure if there'd be any reason to instead hash an earlier struct (either hash `storer`, the K8S objects we input into the parser, or `kongstate`, the Kong entities before we convert them to a decK file struct--see https://github.com/Kong/kubernetes-ingress-controller/blob/6c77c91d31abfdd6bb64767f2b07acf9b5a41ccf/pkg/sendconfig/common_workflows.go#L41), but there probably isn't. If that does make a difference, something is probably wrong and warrants investigation, so hashing the last Go structure (`targetContent`) should be fine.

**Questions on new lock and pass SHA by reference**

What was the reason for the [additional lock](https://github.com/Kong/kubernetes-ingress-controller/pull/1544/files?file-filters%5B%5D=.go#diff-b05f654ea7672e3e05229ff9bbfef27d43246d6c3002cfa49adda74ae2695a4bR66-R68)? It doesn't look like we lock it in more than one place, and I don't know offhand how we'd have had a race condition, even when using a reference to a SHA value rather than a copy.

We should only have one update in progress at a time, correct? `lastConfigSHA` is part of `clientgoCachedProxyResolver` struct, and the goroutine started by `startCacheServer()` only updates that for its CPR on [timer events](https://github.com/Kong/kubernetes-ingress-controller/blob/6c77c91d31abfdd6bb64767f2b07acf9b5a41ccf/railgun/internal/proxy/clientgo_cached_proxy_resolver.go#L230-L231), which are inherently periodic. Was there some sequence of events where an update was ongoing, another timer tick fired and started another update, and the first update finished after the second, updating `lastConfigSHA` with an outdated value? If so, would it make sense to lock in the timer tick handler instead, if only for making that more visible than a lock down in the depths of the sync call tree?

I'm also unclear on the change to a reference (the `oldSHA *[]byte` instead of `oldSHA []byte` in `PerformUpdate()`) itself. It seems a bit odd as we do still return the SHA value at the end, which eventually passes it by value back up to the `clientgoCachedProxyResolver` instance.

**Comment by ccfishk** [comment]
> custom entity blob's contents

#

> At minimum, this needs to account for the [custom entity blob's contents](https://github.com/Kong/kubernetes-ingress-controller/blob/next/pkg/deckgen/deckgen.go#L27-L29). Hashing `targetContent` only means that the controller won't reconfigure Kong when a user changes custom entities only. Probably easiest to do that by creating a temporary struct containing both `targetContent` and the custom entities blob and running `hashstructure.Hash()` on that.

> 
> **Questions on the hash strategy**
> 
> Can you show a small example how the change here clears the issue, e.g. a `targetContent` where hashing the `file.Content` version (what this change does) results in a consistent hash, but hashing the `json.Marshal(targetContent)` of the same `targetContent` does not? Is this something where you could add a regression unit test?

[Jimin] If you look at this code block starting from https://github.com/Kong/kubernetes-ingress-controller/blob/next/pkg/deckgen/deckgen.go#L17, there is no difference between targetContent and customEntities, unless you give me a concrete example, or i need find it out.

> 
> It seems like the advantage of hashstructure is that we'd be able to make use of the SlicesAsSets option, so that if we generate Kong routes `{routeA, routeB}` in one parser build and `{routeB, routeA}` on another we do not update config, because that order doesn't actually matter (the set of Kong routes is indeed a set in the maths sense), it's just an artifact of how Go loops work when building slices from a range. However, we don't use that option here.
> 
> I wouldn't expect `json.Marshal()` to permute the order of objects in its input as both Go slices and JSON arrays _do_ care about order, so it should preserve that: if you generate the same `targetContent` twice and marshal it, you get the same JSON blob. Thus it seems like this change without the ignore slice order option wouldn't change the end result--if we generate `targetContent`s with the same items in different orders (an issue that definitely has affected us in the past), we still wind up with different hashes with this proposed change.
  [Jimin] Justification of changing from checksum to hash - unique and efficiency. The purpose of checksum or hash is to avoid repeat configuration sync, and we do intend to reduce configuration processing time (compose sync, sync, status update all-inclusive). Will provide an example per your request. 
> 
> Not sure if there'd be any reason to instead hash an earlier struct (either hash `storer`, the K8S objects we input into the parser, or `kongstate`, the Kong entities before we convert them to a decK file struct--see
> 
> https://github.com/Kong/kubernetes-ingress-controller/blob/6c77c91d31abfdd6bb64767f2b07acf9b5a41ccf/pkg/sendconfig/common_workflows.go#L41
> 
> ), but there probably isn't. If that does make a difference, something is probably wrong and warrants investigation, so hashing the last Go structure (`targetContent`) should be fine.
> **Questions on new lock and pass SHA by reference**
> 
> What was the reason for the [additional lock](https://github.com/Kong/kubernetes-ingress-controller/pull/1544/files?file-filters%5B%5D=.go#diff-b05f654ea7672e3e05229ff9bbfef27d43246d6c3002cfa49adda74ae2695a4bR66-R68)? It doesn't look like we lock it in more than one place, and I don't know offhand how we'd have had a race condition, even when using a reference to a SHA value rather than a copy.
  [Jimin] This lock is dedicated for proxy lastConfigSHA concurrent updating. Here is how the picture comes into picture 
- every 3 seconds, we trigger cache updating -- read object from cache, parse, process
- the previous kongUpdater function is not done (lastConfigSHA not updated yet), 
   new Updater which brings in the exact same cache objects, which trigger another around updating based on SHA comparison
  earliest time updating lastConfigSHA avoids the another round, which earns some performance.
 
 We update lastConfigSHA only once, and change the parameter to pointer to reflect change on the fly.
  Hope this helps to clarifying the case.
> 
> We should only have one update in progress at a time, correct? `lastConfigSHA` is part of `clientgoCachedProxyResolver` struct, and the goroutine started by `startCacheServer()` only updates that for its CPR on [timer events](https://github.com/Kong/kubernetes-ingress-controller/blob/6c77c91d31abfdd6bb64767f2b07acf9b5a41ccf/railgun/internal/proxy/clientgo_cached_proxy_resolver.go#L230-L231), which are inherently periodic. Was there some sequence of events where an update was ongoing, another timer tick fired and started another update, and the first update finished after the second, updating `lastConfigSHA` with an outdated value? If so, would it make sense to lock in the timer tick handler instead, if only for making that more visible than a lock down in the depths of the sync call tree?
   [Jimin] Yes, each controller reconcile objects and call the OnUpdate to en-object-into-cache, and the every 3 seconds, the cache process the objects based on ingress
> 
> I'm also unclear on the change to a reference (the `oldSHA *[]byte` instead of `oldSHA []byte` in `PerformUpdate()`) itself. It seems a bit odd as we do still return the SHA value at the end, which eventually passes it by value back up to the `clientgoCachedProxyResolver` instance.
[Jimin] the advantage of pointer reference is updating cross functions coz data is written to the unique address (proxy.lastConfigSHA)

#

**Review by rainest — CHANGES_REQUESTED** [review]
> there is no difference between targetContent and customEntities

Not sure I follow this assertion--they are separate variables and their contents will be different. `customEntities` contains the user-provided YAML from the Secret specified in `–kong-custom-entities-secret`. We use this to let users provide [Kong entities that we have no Go structs for](https://docs.konghq.com/kubernetes-ingress-controller/1.3.x/guides/configuring-custom-entities/), and concatenate that with the rendered `targetContent` bytestring to get our complete config document, hence why `GenerateSHA()` is also checking the combined content. We do definitely need to account for its content in the hash input.

I don't have a perfect mental model for the concurrency behavior when we hit the "previous update already in progress, ticker fired again" scenario, but it does sound like that was what you were looking at, and I know it can happen. There are some existing mechanisms to deal with it in DB-less mode (Kong just returns a 429 if another update is ongoing), though I'm not sure exactly what happens in DB-backed mode (probably nothing we want--I think the decK reconciliation attempts could fight one another if you run multiple concurrently), but there's ultimately no reason to attempt concurrent updates, so a controller-based approach would be an improvement.

For that, could you move the lock up into [the top-level ticker event case](https://github.com/Kong/kubernetes-ingress-controller/blob/6c77c91d31abfdd6bb64767f2b07acf9b5a41ccf/railgun/internal/proxy/clientgo_cached_proxy_resolver.go#L230-L236), and have it immediately exit if the lock is held? It looks like this would entail converting it to a semaphore, using `TryAcquire()`, and in the event that the semaphore is held/a previous update is in progress, the `syncTicker` case does nothing (there's no point in attempting a concurrent update, and the next ticker event that does grab the semaphore will apply new changes since if needed).

That would be more visible than handling it down in `sendconfig.PerformUpdate()` and hopefully save on some additional unnecessary work (there's no reason to go halfway into update handling if we're ultimately going to wait anyway). Dropping events here should make more sense than locking, as we don't need to guarantee every event completes. The latest cache contents at the present are always what we want to apply; there's no reason to try and go and handle events that couldn't complete earlier since you can always just look at the current cache contents to build the desired config.

@shaneutt as the original author of the update code here, does the reasoning above look sound? For both you and @ccfishk, would it make sense to discuss in a call? This is maybe a bit hard to reason about in text and live whiteboarding a visual representation may help.

**Comment by ccfishk** [comment]
working on improving addressing issue and solution. convert to draft temporarily.

**Review by rainest — COMMENTED** [review]
To echo @shaneutt's comment earlier in chat, adding a hard external dependency on Redis is a significant change and poses a barrier to adoption that I don't think we'd want to introduce--the controller is currently entirely self-contained, and that's good. Absent evidence of clear end user issues with the existing flow, this feels like premature optimization with a pretty heavy cost.

To move forward with this I think we'd want a more thorough analysis of the performance issues this seeks to solve and demonstration of how it solves them, evidence from user reports if available, and a means to disable/continue using the old implementation that doesn't rely on Redis.

Timing-wise, I think we'd be hard-pressed to get this into 2.0 since we intend to have a feature frozen beta release soon, and this wasn't originally planned for it. IMO it'd make sense to plan it for a post-2.0 minor release instead.

**Comment by ccfishk** [comment]
> To echo @shaneutt's comment earlier in chat, adding a hard external dependency on Redis is a significant change and poses a barrier to adoption that I don't think we'd want to introduce--the controller is currently entirely self-contained, and that's good. Absent evidence of clear end user issues with the existing flow, this feels like premature optimization with a pretty heavy cost.
> 

[Jimin] First of all, please help to understand how current implementation introducing a bottleneck for kic2.0.

 Every DefaultSyncSeconds we invoke Updator (https://github.com/Kong/kubernetes-ingress-controller/blob/next/railgun/internal/proxy/clientgo_cached_proxy_resolver.go#L225). And it reads all ingresses (10, 100, 1000, etc) objects from cache, do as following
- Calculate its checksum
- Compare this checksum with persisted checksum and detect newly added ingress
- If there is new data within the data, KIC sends requests to deck (https://github.com/Kong/kubernetes-ingress-controller/blob/next/pkg/sendconfig/common_workflows.go#L47), proxy accordingly (https://github.com/Kong/kubernetes-ingress-controller/blob/next/pkg/sendconfig/sendconfig.go#L28), which includes significant redundancy

  Here is a concrete example
  -  Sync 1: 100 ingresses newly configured in cluster
  -  Proxy read 100 ingress data, compose deck struct using 100, calculate checksum using 100, post config to proxy for 100, all the 100 ingresses are completed 
  
  - Sync 2 (3 seconds later): 5 more ingresses newly configured in cluster, totally, 105
  - Proxy read 105 ingress data, compose deck struct using 105, calculate checksum using 105; post config to proxy for 105, though we only have 5/100 ingress not processed
    This mechanism results in redundancy calculation, repeated message communication which bring extra burden to other module. If the data goes to 1000, 10000, ... the redundancy is unprecedented, and becomes a bottleneck. 

> To move forward with this I think we'd want a more thorough analysis of the performance issues this seeks to solve and demonstration of how it solves them, evidence from user reports if available, and a means to disable/continue using the old implementation that doesn't rely on Redis.

[Jimin] Also, please be understood this limitation is introduced by the nature of our ingress, some special -- we dont have a pre-defined expected behavior of our custom resource (ingressess). our reconcile function has to blindly put everything into the proxy cache for processing coz we cant not compare between existing CR status and expected CR status. We're leveraging logic checksum to detect any data change of the ingress and take it as an expected status. That is fine since both create/configure operation definitely results in CR change.
> 
> Timing-wise, I think we'd be hard-pressed to get this into 2.0 since we intend to have a feature frozen beta release soon, and this wasn't originally planned for it. IMO it'd make sense to plan it for a post-2.0 minor release instead.
[Jimin] Definitely, agree, we should add more use cases testing deployment regression.

**Review by mflendrich — CHANGES_REQUESTED** [review]
I agree with what @rainest said above and I'd summarize my own thoughts this way:

- there is no visible performance regression in 2.0 that we'd be solving here: the fact that every update causes a complete rebuild of the configuration has been the case for KIC 1.x since always (unless I missed something and 2.0 regresses this) 
- adding a dependency to Redis is a big deal, like Travis said above
- this change (effectively: rebuild of the synchronization mechanism) is a cross-cutting change that needs a lot of caution when executed, and is way out of planned scope for Railgun, and maintainers need to focus their attention on getting the 2.0 scope executed upon 100% before making further optimizations.

Therefore, the conclusion is that, if there's no regression in 2.0 in how rebuilding the entire configuration brings lower performance than 1.x, then this change won't go to 2.0 due to the reasons explained above. Because of that, the PR cannot go to `next` because `next` is our 2.0 mainline at the moment.


My suggested action (hence "changes requested") for this PR are:
- this PR to target a future release (maybe 2.1 or 2.2 or so) and not 2.0. This means no merging to `next` before we cut 2.0.
- adjust our focus: prioritize _getting regressions in 2.0 ironed out and getting 2.0 production-quality_ over adding new features and optimizations for things not impacted by the 1.3->2.0 architectural upgrade
- demonstrate performance gain from this change

**Comment by mflendrich** [comment]
Decision: revisit the problem that this PR is trying to solve during the beta testing process for 2.0.

**Review by shaneutt — CHANGES_REQUESTED** [review]
I know we're waiting until post 2.0 beta to revisit this, and normally I wouldn't just block a PR outright but I feel strongly that I would like to be considered a stakeholder in this one, I want to be involved before we merge it please :bow:

**Comment by ccfishk** [comment]
Update: after more debug/clarification/discussion, I come to realize the real bottleneck is latest config wins under kong post /config. 
And the solution I tried to apply is only update changed ingress which can remove previous config under kong. So, I close the PR atm.
During debug, I am also aware unclear empty kong state {[] [] [] [] [] [] 0.0.0} update, would like to sort that out.

**Comment by ccfishk** [comment]
low priority, close atm.

**Pull request closed without merging**
