### PR TITLE
docs(readme): add KGO instructions alongside Helm

### PR DESCRIPTION
**Pull request by mflendrich**
**What this PR does / why we need it**:

Before this PR - the README quick start only has the Helm option.
After this PR - the README has not only Helm but also KGO as an option.

**Which issue this PR fixes**:

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] ~the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR~ n/a

### CODE REVIEW

**Review by programmer04 — APPROVED** [review]
⚠️  In the docs https://docs.konghq.com/gateway-operator/1.0.x/get-started/kic/install/ old version of CRDs `v0.8.1` is recommended instead of `v1.0.0`

**Review by pmalek — COMMENTED** [review]
We have not tested KGO against KIC 3.0 and there has been no release  after v1 of Gateway API. We're not sure what's the OOTB experience on this one. It will most likely work it hasn't been tested yet.

**Comment by pmalek** [comment]
> ⚠️ In the docs https://docs.konghq.com/gateway-operator/1.0.x/get-started/kic/install/ old version of CRDs `v0.8.1` is recommended instead of `v1.0.0`

That's because there were no KGO releases after v1 of Gateway API.

I've created https://github.com/Kong/gateway-operator/issues/1188 to track this.

**Comment by mflendrich** [comment]
Blocked by https://github.com/Kong/gateway-operator/issues/1188

**Review by pangruoran — APPROVED** [review]

**Review by mlavacca — APPROVED** [review]

**Comment by pmalek** [comment]
Let's wait for 1.1 release which will include it

**Comment by randmonkey** [comment]
Looks like it still waits for the KGO docs in the link to update: https://github.com/Kong/docs.konghq.com/pull/6544

**Comment by programmer04** [comment]
And also waits for https://github.com/Kong/docs.konghq.com/pull/6585

**Pull request merged**
