### PR TITLE
tests(konnect): add e2e test covering Konnect config push

### PR DESCRIPTION
**Pull request by czeslavo**
**What this PR does / why we need it**:

Adds an E2E test that covers Konnect configuration push. The test requires `TEST_KONG_KONNECT_ACCESS_TOKEN` env variable to be set in order to create a Runtime Group and populate a client certificate for it in Konnect dev environment.

In order to communicate with runtime-groups and runtime-groups-config APIs, it uses auto-generated clients that we intend eventally move outside of this repository. There's an ongoing effort in Konnect team to create a repository for them. I've created an issue to track this: https://github.com/Kong/kubernetes-ingress-controller/issues/3550.

E2E tests run: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4176874158

**Which issue this PR fixes**:

Part of #3437.

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

**Comment by randmonkey** [comment]
How did the client generated?

**Comment by czeslavo** [comment]
> How did the client generated?

PTAL https://github.com/Kong/platform-api/pull/87.

**Review by rainest — COMMENTED** [review]
Is there a way to use the standard HTTP error constants from https://pkg.go.dev/net/http#pkg-constants ? It seems odd to define our own. That appears to be something the OpenAPI generator code did, but that seems off given that we're not (AFAICT) adding anything beyond the standard HTTP semantics.

**Review by pmalek — APPROVED** [review]

**Comment by pmalek** [comment]
> It seems odd to define our own. That appears to be something the OpenAPI generator code did, but that seems off given that we're not (AFAICT) adding anything beyond the standard HTTP semantics.

I agree. Although given that we have #3550, and that generated code will indeed land in a separate repo I think: whatever 🤷

**Comment by czeslavo** [comment]
> Is there a way to use the standard HTTP error constants from https://pkg.go.dev/net/http#pkg-constants ? It seems odd to define our own. That appears to be something the OpenAPI generator code did, but that seems off given that we're not (AFAICT) adding anything beyond the standard HTTP semantics.

Please take a look at the OAPI spec here https://github.com/Kong/platform-api/pull/87/files. Short answer in the context of this PR will be: yeah, that's basically what the oapi-codegen gives us as an output from the spec. 

It's a little bit different than just defining consts for status codes, because it's defining a separate **type** for each of them, and they're used as fields in the `JSON***` body types. It's because of the way it's defined in our spec.

**Pull request merged**
