### PR TITLE
Enforcing SSL default true for Postgres Database

### PR DESCRIPTION
**Pull request by swapnild2111**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by hbagdi** [comment]
@swapnild2111 From what I can read in Postgres documentation, it seems like TLS with a self-signed certificate won't work with the Postgres Docker image.
This leads to the case where one needs to generate a certificate, put it inside k8s and then mount it as well.
Is there a simpler way out for this?

**Comment by swapnild2111** [comment]
Hello - I did not modify anything apart from making SSL param true.
I know Azure needs `https://www.digicert.com/CACerts/BaltimoreCyberTrustRoot.crt.pem` certificate to connect to Postgres SSL - but then I haven't done it & it still works fine.

**Comment by hbagdi** [comment]
The outstanding question here is if Postgresql container will automatically generate a self-signed certificate or do we need to supply one here.

**Comment by hbagdi** [comment]
Postgres doesn't generate default certificates, hence enabling this by default is going to increase friction for users to setting up Kong.

Thanks for the PR @swapnild2111!

**Pull request closed without merging**
