### PR TITLE
ci: remove GHA environment for nightly build

### PR DESCRIPTION
**Pull request by tao12345666333**
**What this PR does / why we need it**:

**Which issue this PR fixes**:

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

**Comment by tao12345666333** [comment]
The job successed https://github.com/Kong/kubernetes-ingress-controller/actions/runs/8480883639

**Comment by czeslavo** [comment]
@tao12345666333  Can you please explain why we're removing it? Is it because we do not need the environment's secrets?

**Comment by randmonkey** [comment]
The PR did not have the "Enable auto merge" when I open the page.

**Comment by tao12345666333** [comment]
> @tao12345666333 Can you please explain why we're removing it? Is it because we do not need the environment's secrets?

@czeslavo Sorry, I forgot to update the description. It has been updated now.

@randmonkey Don't worry, we already have the context.

**Pull request merged**
