### PR TITLE
test: add timeout to context to trigger cleanup on wait for env ready

### PR DESCRIPTION
**Pull request by randmonkey**
**What this PR does / why we need it**:

Add a `timeout` to context passed into `env.WaitForReady` to trigger returning errors and cleanup, to avoid the timeout of test command that will not call the env cleanup, thus no diagnostics are outputted.  

**Which issue this PR fixes**:

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- ~~[ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR~~  Just affect integration tests

### CODE REVIEW

**Review by pmalek — APPROVED** [review]
While this looks good, my prior testing proved that when we want to get the diagnostics from the cluster that failed to get ready there's not much that can be obtained because `kubectl` invocations will fail.

It might help in case addons didn't get ready in time.

**Comment by randmonkey** [comment]
> While this looks good, my prior testing proved that when we want to get the diagnostics from the cluster that failed to get ready there's not much that can be obtained because `kubectl` invocations will fail.
> 
> It might help in case addons didn't get ready in time.

I think these should be added on KTF side to dump logs of `kind` . Do we have the issue now?

**Comment by randmonkey** [comment]
> > 
> 
> I don't believe we have an issue for this.

https://github.com/Kong/kubernetes-testing-framework/pull/591 Does this PR help?

**Comment by pmalek** [comment]
> > > 
> > 
> > 
> > I don't believe we have an issue for this.
> 
> [Kong/kubernetes-testing-framework#591](https://github.com/Kong/kubernetes-testing-framework/pull/591) Does this PR help?

It might, I'm not sure though.

**Pull request merged**
