### PR TITLE
chore(tests): improve TestUDPIngressTCPIngressCollision stability

### PR DESCRIPTION
**Pull request by czeslavo**
**What this PR does / why we need it**:

Improves `TestUDPIngressTCPIngressCollision` stability by querying a hostname already known to the CoreDNS spawned for the purpose of the test, saving time spent on calling external DNS. 

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

~~- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR~~

### CODE REVIEW

**Comment by pmalek** [comment]
Rather than checking the changelog box in the PR description you can cross it out or remove it if it's not relevant for your PR (e.g. no user facing changes)

**Comment by jrsmroz** [comment]
Just out of curiosity, how much time can be saved here?

**Comment by czeslavo** [comment]
> Just out of curiosity, how much time can be saved here?

I've got no hard data here, but it will depend on a context of network bandwidth the test are run in. In my case it wasn't even just time saving, but rather making the test pass - since it was failing due to DNS query taking longer than default 2s timeout. 

It shouldn't take that long, but I still wasn't able to find out what's the root cause. Making the test independent of the external services has helped though.

**Review by rainest — APPROVED** [review]
We should maybe define a non-real hostname but whatever.

**Pull request merged**
