### PR TITLE
chore(deps) bumps for go-logr 1.x compatibility

### LINKED ISSUE #2045: Update to GOLOGR v1.x
Automatic updates weren't able to update us to `go-logr` v1:

https://github.com/Kong/kubernetes-ingress-controller/pull/2043

The purpose of this issue is to take the time to update this and manually deal with the backwards incompatible changes.

### LINKED ISSUE #2072: Dependency updates for Kubernetes v1.23.x
### Problem Statement

Several recent dependency updates for a minor version bump aligning with Kubernetes `v1.23.x` were not backwards compatible:

- https://github.com/Kong/kubernetes-ingress-controller/pull/2060
- https://github.com/Kong/kubernetes-ingress-controller/pull/2061
- https://github.com/Kong/kubernetes-ingress-controller/pull/2062
- https://github.com/Kong/kubernetes-ingress-controller/pull/2063
- https://github.com/Kong/kubernetes-ingress-controller/pull/2064
- https://github.com/Kong/kubernetes-testing-framework/pull/173
- https://github.com/Kong/kubernetes-testing-framework/pull/174
- https://github.com/Kong/kubernetes-testing-framework/pull/175
- https://github.com/Kong/kubernetes-testing-framework/pull/176

As seen above the dependabot updates were not able to complete.

The purpose of the task is to make these updates manually and make the code adjustments needed to support the new versions.

- [ ] perform the dependency updates here in KIC
- [ ] ALSO perform the dependency updates in [KTF](https://github.com/kong/kubernetes-testing-framework)

### PR DESCRIPTION
**Pull request by rainest**
**What this PR does / why we need it**:
Bumps go-logr to 1.x and bumps things that depend on go-logr to versions
compatible with 1.x.

Updates a logrusr function name that changed.

Return an empty struct instead of nil where nil returns are no longer
allowed.

Bump Kubernetes dependencies to 0.23 because controller-runtime requires
it.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2045 
fixes #2072

### CODE REVIEW

**Comment by rainest** [comment]
Was there another PR for #2072? I'm not seeing one linked.

**Comment by shaneutt** [comment]
Oh sorry my bad, no there isn't carry on.

**Comment by rainest** [comment]
With the removal of the Knative libs from tests in favor of the dynamic client, we're good to go. Note that we do still use their API lib (and the Knative devs suggest that, in general, stuff that mixes their libs and controller-runtime may cause further dependency hell in the future), but it's not broken now, so leaving that in place. If we need to replace it we'd just need to duplicate a constant from the looks of it.

**Review by shaneutt — APPROVED** [review]
Thanks for taking the time to sort this out :vulcan_salute:

**Pull request merged**
