### PR TITLE
chore: update k8s versions in nightly workflow

### PR DESCRIPTION
**Pull request by pmalek**
**What this PR does / why we need it**:

This PR changes `nightly` workflow in the following way:

* removes unavailable k8s 1.20 when running integration tests on GKE
* adds k8s 1.24 when running integration tests on GKE
* fixes kubernetes version variable name reference (dash vs underscore) 
* bumps the "current" version of k8s from 1.24.2 to 1.25

### CODE REVIEW

**Comment by pmalek** [comment]
Can't run `nightly` workflow on non `main` branch due to environment protection rules : https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3059138605 😞 

```
Branch "update-k8s-versions-in-nightly" is not allowed to deploy to Docker Push due to environment protection rules.
```

**Comment by pmalek** [comment]
I run `TestIngressClassRegexToggle` locally and it didn't fail 😒

**Comment by jrsmroz** [comment]
TestTLSRouteEssentials failed. Is this a new flake?

**Comment by jrsmroz** [comment]
This PR needs to pull the latests changes that unblock the failing tests in order to be merged.

**Review by czeslavo — APPROVED** [review]

**Pull request merged**
