### PR TITLE
Allow KongIngress for individual Ingress backends

### PR DESCRIPTION
**Pull request by mcriss**
What this PR does / why we need it:
This PR allows the use of KongIngress objects for individual Ingress backends and addresses incorrect annotation usage in the custom-types.md

### CODE REVIEW

**Comment by gerred** [comment]
Hi @mcriss, I'm taking a look at all of the backed up PRs and issues now. Once I've had a chance to look, I'll review!

**Comment by linydquantil** [comment]
@gerred  the latest kong version is 0.14.0, when did you upgrade to the latest version

**Comment by hbagdi** [comment]
Hi @linydquantil,
Tying `KongIngress` with service names can have unintended side effects of a `KongIngress` resource being picked up when one doesn't want it so.

Since this is a service level thing, would a better approach be to create a separate Ingress resource for the services that need that override and apply the annotation specifically.

Another thought here is that users will have to think more carefully about how to name their `KongIngress` objects if this feature exists and makes things more cumbersome than needed.

 Thoughts?

**Comment by hbagdi** [comment]
> At the time of submitting this PR, multiple ingress resources with the same host resulted in the duplicate host ingress to get ignored.

Yes, this is a problem currently that we are aware of and is something we want to support.

I'll close the PR for now but feel free to re-open if needed.

**Pull request closed without merging**
