### PR TITLE
[N/A] adding a basic helm chart. Work in progress and provided as is

### PR DESCRIPTION
**Pull request by dcherniv**
**What this PR does / why we need it**:
helm is a de-facto standard for installing yaml definitions on kubernetes.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
no issue.

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by dcherniv** [comment]
@hbagdi for your consideration.

**Comment by hbagdi** [comment]
@dcherniv Kong's official Helm chart already supports Kong Ingress Controller deployment: https://github.com/helm/charts/tree/master/stable/kong#kong-ingress-controller

**Comment by dcherniv** [comment]
@hbagdi makes sense. I couldn't find it in this repo and the documentation seemed to not mention it existing.

**Comment by hbagdi** [comment]
@dcherniv updated now: https://github.com/Kong/kubernetes-ingress-controller/commit/b0a40ae3d7ed9a1e3c4729ba01407be69d8caae6

Thanks for the PR!
Please feel free to send PRs to `helm/charts` repository in case you encounter any issues or wish to give any feedback.

**Pull request closed without merging**
