### PR TITLE
test: run cronjob to test against kong nightly

### LINKED ISSUE #2850: Run tests against kong gateway nightly
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

We have created GH action to run integration tests against kong nightly build to test the compatibility with kong gateway 3.0, but we stopped it since the test is unstable. Now kong gateway is expected to be released soon, we need to restart the tests for compatibility tests

### Proposed Solution

- enable `test-nightly` action in a cronjob.

### Additional information

_No response_

### Acceptance Criteria

- [ ] `test-nightly` could run to test compatibility with kong 3.0.

### PR DESCRIPTION
**Pull request by randmonkey**
**What this PR does / why we need it**:

run `test-nightly` agianst kong nightly build to test the compatibility with kong 3.0.

**Which issue this PR fixes**:

fixes #2850 

**Special notes for your reviewer**:

I changed the trigger from run for each PR to run daily. WDYT is the proper way to run these tests?

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

**Comment by randmonkey** [comment]
I tried to run the `test-nightly` manually, but it is skipped. Seems that we need to enable it from settings.

**Comment by pmalek** [comment]
I believe that this will revert back to the chaos of failures that we had previously.

Perhaps we could first try to address whatever's to address in PRs (by adding label `ci/run-nightly` label) and only when we get to a point where it's stable enough for us then we could add the schedule back in.

**Review by rainest — COMMENTED** [review]
Aside from the question of whether we should enable cron again, the gateway has fixed whatever issues they were having with the OSS builds. The `kong/kong:master-nightly-alpine` now does track the current OSS master build; we should add an additional job for it in DB-less mode. We could also run Postgres for it, but it's not as useful given the overlap.

**Review by rainest — CHANGES_REQUESTED** [review]
This is effectively superseded by https://github.com/Kong/kubernetes-ingress-controller/pull/2885, correct? That uses specific 3.x tags instead of the master build, but we'll presumably change to the latter after the 3.x release.

We do want the tests-nightly job to optionally run on PRs (or just always run on PRs--see below). Workflow dispatch can sort of accomplish that, but it's not automatically linked to the PR. If this remains optional, what we really want is to solve the clunky label remove/re-add dance required to re-run it.

https://github.com/rainest/kubernetes-ingress-controller/actions/runs/2930000460/workflow was my attempt at that based on some Github community posts, but it didn't quite work because it'd run even without the label, apparently without checking the condition, as seen in the run for https://github.com/rainest/kubernetes-ingress-controller/pull/66

Enabling these on all PRs again may also be fine. The apparent instability of the master builds was, I think, mostly due to the regex change sneaking in shortly after we added the test, and our not realizing how that affected almost all tests because a common helper function created regex routes.

**Comment by randmonkey** [comment]
> This is effectively superseded by #2885, correct? That uses specific 3.x tags instead of the master build, but we'll presumably change to the latter after the 3.x release.
> 
> We do want the tests-nightly job to optionally run on PRs (or just always run on PRs--see below). Workflow dispatch can sort of accomplish that, but it's not automatically linked to the PR. If this remains optional, what we really want is to solve the clunky label remove/re-add dance required to re-run it.
> 
> https://github.com/rainest/kubernetes-ingress-controller/actions/runs/2930000460/workflow was my attempt at that based on some Github community posts, but it didn't quite work because it'd run even without the label, apparently without checking the condition, as seen in the run for [rainest#66](https://github.com/rainest/kubernetes-ingress-controller/pull/66)
> 
> Enabling these on all PRs again may also be fine. The apparent instability of the master builds was, I think, mostly due to the regex change sneaking in shortly after we added the test, and our not realizing how that affected almost all tests because a common helper function created regex routes.

Now we have tests against Kong 3.0, it is OK to just keep the tests for nightly run for PRs with certain label, as we do now. Close this and #2850.

**Pull request closed without merging**
