### PR TITLE
chore: add manifests and e2e tests for postgres with gateway discovery

### PR DESCRIPTION
**Pull request by randmonkey**
**What this PR does / why we need it**:

Add example manifests for deploying KIC with gateway discovery + multiple kong gateways using postgres DB backend, and also add an e2e test case to verify the correctness. 

**Which issue this PR fixes**:

part of #3606 

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

**Comment by randmonkey** [comment]
e2e runs for this PR: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4302083962

**Comment by pmalek** [comment]
I'd say we wait with this until #3629 gets merged.

**Comment by randmonkey** [comment]
block this until we want to support Gateway Discovery with DB-backed gateways.

**Comment by pmalek** [comment]
I believe that since we have https://github.com/Kong/kubernetes-ingress-controller/blob/c39e31ec09f0e144e659dd53050a907f0d853dd7/test/e2e/all_in_one_test.go#L259-L274 already we do not need this change. Closing this but feel free to reopen @randmonkey if you feel there's still something to follow up on.

**Pull request closed without merging**
