### PR TITLE
feat(rewrite): Remove braces from the rewrite annotation format

### PR DESCRIPTION
**Pull request by mheap**
**What this PR does / why we need it**:

Replaces the `${1}` rewrite format with `$1` to be more intuitive to other pattern matching libraries.

**Which issue this PR fixes**:

N/A

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR <- Does this need a changelog entry as the feature hasn't been shipped yet?

### CODE REVIEW

**Comment by mheap** [comment]
Looks like the linter failed. When trying to lint locally I get the following error:

```
❯ make lint
./scripts/verify-tidy.sh
go: go.mod file indicates go 1.21, but maximum version supported by tidy is 1.19
make: *** [verify.tidy] Error 1
```

**Comment by pmalek** [comment]
> Looks like the linter failed. When trying to lint locally I get the following error:
> 
> ```
> ❯ make lint
> ./scripts/verify-tidy.sh
> go: go.mod file indicates go 1.21, but maximum version supported by tidy is 1.19
> make: *** [verify.tidy] Error 1
> ```

I assume you're running go 1.19 then? [This](https://github.com/Kong/kubernetes-ingress-controller/blob/09975813ed3a6ffd9eef5272f286d5ae08a65b39/go.mod#L3) requires at least go 1.21 to build KIC.

**Comment by mheap** [comment]
```
==> Upgrading go
  1.19.4 -> 1.21.1
```

That'd do it! Will fix the linting errors + push

**Review by czeslavo — APPROVED** [review]

**Comment by czeslavo** [comment]
> Does this need a changelog entry as the feature hasn't been shipped yet?

I think not. The original changelog entry

> `konghq.com/rewrite` annotation has been introduced to manage URI rewriting 

doesn't mention what syntax is used so it's still valid. Maybe we could just add a link to this PR under the entry?

**Review by czeslavo — APPROVED** [review]

**Pull request merged**
