### PR TITLE
fix(e2e): proper checking if Kong Enterprise has valid license and remove all-in-one-dbless-k4k8s-enterprise.yaml

### PR DESCRIPTION
**Pull request by programmer04**
**What this PR does / why we need it**:

Firstly manifest [all-in-one-dbless-k4k8s-enterprise.yaml](https://github.com/Kong/kubernetes-ingress-controller/blob/2e0326d5b4b986c043e59c26b28fb317332c6748/deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml) is identical (almost) to [all-in-one-dbless-enterprise.yaml](https://github.com/Kong/kubernetes-ingress-controller/blob/2e0326d5b4b986c043e59c26b28fb317332c6748/deploy/single/all-in-one-dbless-enterprise.yaml) that is not used anywhere and has a mistake - it doesn't reference any secret. Replace usage of manifest  `all-in-one-dbless-k4k8s-enterprise.yaml` with a consistent one `all-in-one-dbless-enterprise.yaml`.

It should crash test e2e test `TestDeployAllInOneEnterpriseDBLESS`, but it doesn't happen.
Enterprise Kong Gateway returns information about being Enterprise version no matter the license existence/validity. E.g. every time header with
```
server: kong/3.3.1.0-enterprise-edition
```
is returned. Hence manifest [all-in-one-dbless-enterprise.yaml](https://github.com/Kong/kubernetes-ingress-controller/blob/002ff5dd54ef05d05d691eaea307b0aa8ada8dc5/deploy/single/all-in-one-dbless-enterprise.yaml) that doesn't set variable `KONG_LICENSE_DATA` don't break respective tests. This PR improves the `verifyEnterprise` function to use endpoint `/consumer_groups` that is only available in the Enterprise edition to robustly test not only the version of a Kong Gateway but also the validity of a license. Now it crashes a test.

Fix manifest `all-in-one-dbless-enterprise.yaml` to include `KONG_LICENSE_DATA`.

**Special notes for your reviewer**:

In Kong Gateway endpoint `/licenses` is available, but manual tests show that it returns `200` in both versions of Kong Gateway and the body of it was empty even when a valid license was configured in Kong Gateway. Maybe it's something to report to the Kong Gateway team.

- for the first commit https://github.com/Kong/kubernetes-ingress-controller/pull/4354/commits/bb6f63f9d3f1abd71886227338d52a769a088653
  ```sh
  make test.e2e GOTESTFLAGS="-count 1" E2E_TEST_RUN=TestDeployAllInOneEnterpriseDBLESS 
  ```
  ends with success (variable `KONG_LICENSE_DATA` has to be set), but it's wrong. The license is missing.

- for fixed `verifyEnterprise` https://github.com/Kong/kubernetes-ingress-controller/pull/4354/commits/24b70a309691abdb13bc2b8587264d63545ebaad
as expected the above fails

- for fixed manifest `all-in-one-dbless-enterprise.yaml` https://github.com/Kong/kubernetes-ingress-controller/pull/4354/commits/50b191d865f33d8409f4a4375c4029354f822724
everything passes, what verifies e2e run on branch

A separate issue has to be created to adjust documentation for KIC 2.11 to reference this manifest. It won't break existing configurations, because it's pinned to the version in the docs. E.g. [here](https://docs.konghq.com/kubernetes-ingress-controller/latest/deployment/k4k8s-enterprise/#yaml-manifests).

### CODE REVIEW

**Comment by rainest** [comment]
all-in-one-dbless-k4k8s-enterprise.yaml may have been the target of a bitly link, hence why we kept the ancient name. I can't see it among the targets in our bitly account anymore, however, so it's possible we removed whatever docs were using that bitly link.

We do have bit.ly/k4k8s pointing to https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/master/deploy/single/all-in-one-dbless.yaml and in frequent use somewhere, but no others still active AFAICT (the dashboard shows links used in the last 30 days).

**Review by rainest — CHANGES_REQUESTED** [review]
This would leave us without any "legacy" (single controller+proxy Pod) Enterprise install.

Although we don't appear to have any more bitly links to it, we do reference the removed manifest from `app/_src/kubernetes-ingress-controller/deployment/k4k8s-enterprise.md` in docs, and would need to update that.

Not including licenses in the Enterprise all-in-one manifests is, AFAIK, intentional. Enterprise free mode is a normal configuration, and these manifests are designed to give you a working instance with a single apply command. The E2E tests for them are to confirm you do indeed get one, with the expected image, not to verify Enterprise paid functionality (that's all in integration).

We can't configure an optional license Secret, since referencing it will prevent the Pods from starting.

Was there something we wanted to do in E2E that would require a license? We should instead add a helper to patch one in if so.

**Comment by czeslavo** [comment]
> This would leave us without any "legacy" (single controller+proxy Pod) Enterprise install.

I think it was this way already. The removed one is based on `multi-gw` manifests. 

> Although we don't appear to have any more bitly links to it, we do reference the removed manifest from `app/_src/kubernetes-ingress-controller/deployment/k4k8s-enterprise.md` in docs, and would need to update that.

As I understand, that is something @programmer04 mentioned in the `Special notes for your reviewer` ("A separate issue has to be created...").

> Not including licenses in the Enterprise all-in-one manifests is, AFAIK, intentional. Enterprise free mode is a normal configuration, and these manifests are designed to give you a working instance with a single apply command. The E2E tests for them are to confirm you do indeed get one, with the expected image, not to verify Enterprise paid functionality (that's all in integration).
> 
> We can't configure an optional license Secret, since referencing it will prevent the Pods from starting.
> 
> Was there something we wanted to do in E2E that would require a license? We should instead add a helper to patch one in if so.

The [E2Es](https://github.com/Kong/kubernetes-ingress-controller/blob/3ffabd8f802aa72d7aad6493b018b4dc4ad72d18/test/e2e/all_in_one_test.go#L69) already do create a license secret for the `all-in-one-dbless-k4k8s-enterprise.yaml` and adding the secret reference to the `all-in-one-dbless-enterprise.yaml` aligns with them. Test logs like "exposing the admin api so that enterprise features can be verified" tell me that the intention behind them was to verify that the enterprise features do work when you create a proper license secret.

I do get the argument that it's completely valid to run an EE GW in "Free" mode and specifying the secret reference prevents it from running without patching. I think the question is what workflow is more common: using EE manifests 1) with or 2) without a license. By adding the secret reference to manifests, we optimize for making the experience of 1) more straightforward (just create a secret and apply manifests). 

If we decide to not add the secret reference to the manfiests, I'd say we should have *some* place in documentation that would describe how to patch the manifests accordingly to enable the enterprise mode. The existing [article](https://docs.konghq.com/kubernetes-ingress-controller/latest/deployment/k4k8s-enterprise/) leverages the fact that manifests have the secret reference and only creates the secret.

I think that 1) makes more sense - my gut feeling tells me it's a more common scenario (I tried looking into Splunk, but I think we have no telemetry data that would allow differentiating between EE with/without a license). Anyway, both 1) and 2) will work if we adjust the documentation to it. I'd be interested in @mheap opinion on that.

**Comment by mheap** [comment]
We should optimise for 1 - Enterprise build without a license. This is the default for Gateway, and will become the default in KIC 3.0

**Comment by programmer04** [comment]
Surpassed by
- https://github.com/Kong/kubernetes-ingress-controller/issues/4712

hence irrelevant

**Pull request closed without merging**
