### PR TITLE
Add --profiling to 2.x

### PR DESCRIPTION
**Pull request by rainest**
Carry-over from #1408 that cherry-picks the relevant commits. Base changes made a mess of the original PR.

### CODE REVIEW

**Comment by tharun208** [comment]
@rainest, you need to again rebase with the main branch pr as fixed int test failing due to typo

**Comment by tharun208** [comment]
@rainest usually feature PR's get merged to next and then to main or another way around ?. If this is documented under `CONTRIBUTING.md` means helpful.

**Comment by rainest** [comment]
@tharun208 feature PRs go to next, yes. It's mentioned at the end of the https://github.com/Kong/kubernetes-ingress-controller/blob/main/CONTRIBUTING.md#finding-work section.

The only changes that go direct to main are repo metadata (CI changes and the like) and bugfixes that would be released in a patch release.

**Comment by mflendrich** [comment]
This PR is identical to #1417 and we'll need to merge just one of these (both PRs are retries of #1408)

Closing this one in favor of merging #1417 to ensure that the PR is properly attributed to @tharun208.

**Pull request closed without merging**
