### PR TITLE
Use Plugins (GetSchema), Workspaces (Exists,Create), Tags (Exists) me…

### PR DESCRIPTION
**Pull request by mmorel-35**
Use Go-kong client's features
Fixes #1284

### CODE REVIEW

**Review by shaneutt — COMMENTED** [review]
Thanks @mmorel-35 :smiley: 

Since we're already this far, would you mind please adding the update to `go-kong` which this fix provides for?

**Comment by mmorel-35** [comment]
@shaneutt, I'm not sure to understand. What do you expect me to do ?

**Comment by shaneutt** [comment]
> @shaneutt, I'm not sure to understand. What do you expect me to do ?

What I was thinking was since this fixes the problem for #1284 and makes it possible now to upgrade to `go-kong` `v0.18.0`, would you be comfortable with just adding that update as a part of this PR?

e.g.

```
$ go get github.com/kong/go-kong@v0.18.0
```

**Comment by shaneutt** [comment]
Ok in that case if you're not comfortable then no worries. Let's bump for the most recent `next`...

**Review by shaneutt — APPROVED** [review]

**Pull request merged**
