### PR TITLE
Update the title https redirect

### PR DESCRIPTION
**Pull request by zxDiscovery**
**What this PR does / why we need it**:
https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/configuring-https-redirect.md
The readme title doesn't match the context.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
This is not a serious problem, just change the title.

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by hbagdi** [comment]
@zxDiscovery Could you please sign the CLA so that we can merge this in?

**Comment by zxDiscovery** [comment]
I have already signed the CLA, but I don't know why the status still `Pending`? Do I miss something? @hbagdi 
屏幕快照 2020-04-02 上午11 01 54

**Comment by hbagdi** [comment]
Please add the email address you have used to author the commit to your Github account. Or use the email address for your Github account to author the commit.

**Comment by zxDiscovery** [comment]
Thank you for your remind. I re-configure my Github account. Now it works. Please help to review it. Thank you! @hbagdi

**Pull request merged**
