### PR TITLE
Support short domains for Knative cluster local services

### PR DESCRIPTION
**Pull request by nak3**
**What this PR does / why we need it**:

This patch supports short domains for Kntive cluster local services.

After this patch, users can access `hello.default` or
`hello.default.svc` for `hello.default.svc.cluster.local`

Fixes https://github.com/Kong/kubernetes-ingress-controller/issues/803

### CODE REVIEW

**Comment by hbagdi** [comment]
Please rebase on top of the `next` branch.

**Comment by nak3** [comment]
Sure, done.

**Comment by hbagdi** [comment]
Question: Why does knative not populate the Knative Ingress resource with the necessary hosts? It should do so if Knative wants it's services to be accessible on the short domains.

**Comment by hbagdi** [comment]
@nak3 Can we close this since we are taking care of the feature in https://github.com/knative/serving/pull/9100?

**Pull request closed without merging**
