### PR TITLE
chore: fix syntax to match sh in wait-for-migration script

### LINKED ISSUE #2918: script `wait-for-migration` could not run in debian/ubuntu based images
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The script in initContainer `wait-for-migration` of KIC in manifests:
```
- "/bin/sh"
- "-c"
- "while true; do kong migrations list; if [[ 0 -eq $? ]]; then exit 0; fi; sleep 2;  done;"
```
because `[[` is not recognized by `/bin/sh`.
could not be run in kong images based on `ubuntu` or `debian`. affected images includes:
- `kong/kong:3.0.0-alpha.14-ubuntu`
- `kong/kong:3.0.0-alpha.14-debian`

### Expected Behavior

initContainer can run the script and exit normally (with code 0).

### Steps To Reproduce

```markdown
1. change `image` of initContainer `wait-for-migration` to `kong/kong:3.0.0-alpha.14-ubuntu` in `deploy/single/all-in-one-postgres.yaml`
2. run kubectl apply -f deploy/single/all-in-one-postgres.yaml
3. the KIC pod would remain in Init status, and /bin/sh: 1: [[: not found will appear in log of init container.
```

### Kong Ingress Controller version

_No response_

### Kubernetes version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by randmonkey**
**What this PR does / why we need it**:

fixes the wait-for-migration script that cannot match syntax of `sh`. 

**Which issue this PR fixes**:

fixes #2918. 

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

**Review by mlavacca — APPROVED** [review]

**Review by pmalek — APPROVED** [review]
We should take a look into removing https://github.com/Kong/kubernetes-ingress-controller/blob/806ee3913d039140bd8490c783a731d84c7d7739/config/variants/postgres/kong-ingress-postgres.yaml.

I don't see it being used. When I change it and regenerate manifests that does not produce any change. Can't either see it referenced anywhere.

**Comment by randmonkey** [comment]
> We should take a look into removing https://github.com/Kong/kubernetes-ingress-controller/blob/806ee3913d039140bd8490c783a731d84c7d7739/config/variants/postgres/kong-ingress-postgres.yaml.
> 
> I don't see it being used. When I change it and regenerate manifests that does not produce any change. Can't either see it referenced anywhere.

It was included in `config/variants/postgres/kustomization.yaml`:
```
components:
- ./wait/
- ../../image/oss/
```

**Comment by pmalek** [comment]
> config/variants/postgres/kustomization.yaml

https://github.com/Kong/kubernetes-ingress-controller/blob/c14cf387f3fd7b5e413a4ab8c7dfb55d081a081c/config/variants/postgres/wait/kong-ingress-postgres.yaml is included 

https://github.com/Kong/kubernetes-ingress-controller/blob/c14cf387f3fd7b5e413a4ab8c7dfb55d081a081c/config/variants/postgres/kong-ingress-postgres.yaml is not

**Comment by randmonkey** [comment]
close this since it would have a better fix in #2923.

**Pull request closed without merging**
