### PR TITLE
Release 2.1.0

### PR DESCRIPTION
**Pull request by rainest**
**What this PR does / why we need it**:
Releases 2.1.0. Version bumps, some minor updates to outdated release instructions and missed changelog items.

**Special notes for your reviewer**:
As of yet, GKE does not offer 1.23 on rapid. 1.19 is still supported on stable. No changes to the test versions. Not sure about KIND--I'm not seeing a version for that, is it entirely within KTF?

### CODE REVIEW

**Comment by shaneutt** [comment]
> Not sure about KIND--I'm not seeing a version for that, is it entirely within KTF?

Yes, via `WithClusterVersion(version semver.Version)`

https://github.com/Kong/kubernetes-testing-framework/blob/main/pkg/clusters/types/kind/builder.go#L40

**Review by shaneutt — DISMISSED** [review]
:partying_face:

**Review by mflendrich — CHANGES_REQUESTED** [review]
blocked on all checkboxes in https://github.com/Kong/kubernetes-ingress-controller/issues/2110 (now just deck upgrade), otherwise :+1:

**Comment by rainest** [comment]
KTF KIND uses the stable image by default, which is still 1.21 for some reason. GKE matrix will test 1.22, ran 1.23 KIND locally: [test.txt](https://github.com/Kong/kubernetes-ingress-controller/files/7807003/test.txt)

The Knative failure occurs for me consistently locally on all versions, haven't been able to figure that out (for some reason, the Knative application fails to create its Ingress-like, so there's nothing for KIC to configure). Maybe an old bug that'd go away if we updated the test version past 0.18.

Some sort of upstream dependency issue is causing issues with e2e tests:

```
make: *** [Makefile:227: test.integration.enterprise.postgres] Error 1
12:44:18+0200 esenin $ KONG_CLUSTER_VERSION=v1.23.0 make test.e2e | tee /tmp/test_e2e.txt 
GOFLAGS="-tags=e2e_tests" go test -v \
	-race \
	-parallel 8 \
	-timeout 30m \
	./test/e2e/...
go: downloading sigs.k8s.io/kustomize/kyaml v0.13.1
# sigs.k8s.io/kustomize/api/resmap
../../go/pkg/mod/sigs.k8s.io/kustomize/api@v0.10.1/resmap/reswrangler.go:218:19: id.GvknString undefined (type resid.ResId has no field or method GvknString)
FAIL	github.com/kong/kubernetes-ingress-controller/v2/test/e2e [build failed]
FAIL
make: *** [Makefile:241: test.e2e] Error 2
```
We don't use that library outside E2E tests, so it doesn't break the actual build.

**Comment by rainest** [comment]
https://github.com/Kong/kubernetes-ingress-controller/issues/2126 is causing me no end of grief. It ran once successfully and has failed every time after :D 

Not cause for concern between being GWAPI functionality and not having any actually different behavior on Enterprise versus OSS, but kicking the workflows in hopes that it will pass again.

Partial local run of E2E on 1.23:
[test_e2e_prep.txt](https://github.com/Kong/kubernetes-ingress-controller/files/7807517/test_e2e_prep.txt)
[test_e2e.txt](https://github.com/Kong/kubernetes-ingress-controller/files/7807507/test_e2e.txt)

These are "working" but Docker Hub has decided I shouldn't get to pull the Postgres and Istio images anymore today, so those are getting stuck forever on preconditions. Will re-run tomorrow, but they're not a release pre-req (the 1.22 and older tests will run on tag push, this is just for #2097 since we can't run 1.23 on GKE yet and KIND won't run it until they mark it stable).

**Comment by mflendrich** [comment]
> KTF KIND uses the stable image by default, which is still 1.21 for some reason. GKE matrix will test 1.22, ran 1.23 KIND locally: test.txt

I think that (for sake of a healthy CI process) we should set it explicitly in the CI job and have Ci run all the tests rather than relying on manual runs. I advocate for setting this envvar `KONG_CLUSTER_VERSION=v1.23.0` in the CI job config and re-running the test before the release.

> We don't use that library outside E2E tests, so it doesn't break the actual build.

I'm not in favor of releasing with problems like this (or the knative problem). Let's fix (or, at the very least, understand) these first.

**Comment by rainest** [comment]
https://github.com/Kong/kubernetes-ingress-controller/pull/2124/commits/1666bbf1269aa84f152185d5263fc82a2ad440c7 fixes the E2E problem.

The Knative problem isn't new, I've had that occur locally since the test was created. Haven't really looked into it since it doesn't occur in CI and I wasn't much interested in debugging (an extremely old version of) Knative itself.

Shane can maybe comment better on the CI design, but I'm guessing we only do explicit versions on GKE is that a single E2E run is already a pretty heavy load on the Actions runner, and 3-4 simultaneous runs would be :sadmac:, whereas GKE has no such limitation.

**Comment by shaneutt** [comment]
The latest version of Kind has historically dragged a bit behind upstream, but always remains on a fairly recent stable version. This gives us the initial "integration works" testing we want for PRs at a reasonably recent version of Kubernetes, where GKE accounts for the matrix of version compatibility.

I understand that the desire here is to have more up-front delivery of status on version incompatibilities and issues, but the current CI specifically makes a trade off on that so that PR testing runs faster. If we want to start trading speed for coverage, I think we will need to invest further in our testing suite so that it can run tests in a highly targeted manner, and perhaps even use [envtest](https://book.kubebuilder.io/reference/envtest.html) from controller-runtime as an alternative KTF cluster implementation for further speed boosts.

It seems to me that the amount of disruptions like this that we've had in recent months has been pretty low, so I'm not sure that investing in more speed and upfront compatibility testing is justified at this point given other priorities, but we could definitely talk further on this and do some brainstorming.

**Comment by shaneutt** [comment]
> I'm on the fence about Knative, let's chat about this tomorrow. Failing runs are an indication of a project health issue that can easily build up over time.

I'm going to go on record here saying that I think we should be considering the deprecation and removal of knative support, the reasons including:

1. we see very little community/end-user engagement with our knative integration
2. it is a common maintenance burden

**Comment by rainest** [comment]
Rebase to clean up some accumulated garbage and move the changelog to the end. Flake should be cleared with the Enterprise test version bump (which we need anyway, else the TLS passthrough tests are skipped).

**Review by shaneutt — APPROVED** [review]

**Pull request merged**
