### PR TITLE
Fix/kong cluster plugin

### LINKED ISSUE #1361: Fix 2.0 KongClusterPlugin handling
As-is, 2.0 cannot see KongClusterPlugins (see https://github.com/Kong/kubernetes-ingress-controller/pull/1360#issue-654148265).

Initial review indicates that this is because the current KongClusterPlugin type is namespaced: https://github.com/Kong/kubernetes-ingress-controller/blob/e7ca5dd403f95e58dd30c7428afc4d3f76814b9f/railgun/config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml#L10-L17

It should not be, as all controller code that interacts with it expects cluster-level resources by design. Debugging indicates that you can currently create namespaced KongClusterPlugins in the store fine, but the store package can't handle those.

Fixing kubebuilder tags should address this:

```
diff --git a/railgun/apis/configuration/v1/kongclusterplugin_types.go b/railgun/apis/configuration/v1/kongclusterplugin_types.go
index 90b481bf..7a5a741f 100644
--- a/railgun/apis/configuration/v1/kongclusterplugin_types.go
+++ b/railgun/apis/configuration/v1/kongclusterplugin_types.go
@@ -24,6 +24,7 @@ import (
 //+genclient
 //+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
 //+kubebuilder:object:root=true
+//+kubebuilder:resource:scope=Cluster
 //+kubebuilder:subresource:status
 //+kubebuilder:storageversion
```
With that in place, [regenerating code](https://github.com/Kong/kubernetes-ingress-controller/issues/1358) does update the CRD manifest, but not the generated client. `make generate.clientsets` should, AFAIK, be the last remaining step, but it's [giving me trouble](https://gist.github.com/rainest/418d72770a43848414f0e042b8f57283).

Note that the original test from #1360 will need a small change to remove the namespace from its clientset calls once this is fixed.

### PR DESCRIPTION
**Pull request by tharun208**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1361

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

**Comment by rainest** [comment]
Doesn't look like this cleared the [clientset generation issue I ran into previously](https://github.com/Kong/kubernetes-ingress-controller/issues/1361).

https://github.com/Kong/kubernetes-ingress-controller/blob/d3dbeee0d7e31a6378884730cc34a817c58dee76/railgun/pkg/clientset/typed/configuration/v1/kongclusterplugin.go#L58-L77 still has namespace information.

Suppose this is as good enough venue to discuss as any other, since the root of the needed change (the scope annotation in ` railgun/apis/configuration/v1/kongclusterplugin_types.go`) is present: @shaneutt do you know what's actually needed to make kubebuilder regenerate the clientset properly/what I did wrong in the steps described in #1361 ?

**Comment by shaneutt** [comment]
> @shaneutt do you know what's actually needed to make kubebuilder regenerate the clientset properly

Kubebuilder isn't responsible for the clientset, we generate this separately from Kubebuilder using `client-gen`, in theory just running `make generate.clientsets` should be enough to straighten things out.

**Comment by tharun208** [comment]
> Kubebuilder

@shaneutt I used this https://github.com/kubernetes/code-generator/tree/master/cmd/client-gen to re-generate the client-sets but no effect

**Comment by rainest** [comment]
Project names are meaningless to me, it's _all_ kubebuilder :D noted though, I'll try to remember which is which in the future.

After some more searching, that does indicate why my original attempt didn't work: kubebuilder and client-gen both have their own (different) metadata tags, and there's an additional tag needed for client-gen to do its half of the non-namespaced change:

```
git diff apis/configuration/v1/kongclusterplugin_types.go 
diff --git a/railgun/apis/configuration/v1/kongclusterplugin_types.go b/railgun/apis/configuration/v1/kongclusterplugin_types.go
index dea8b10d..01c3723c 100644
--- a/railgun/apis/configuration/v1/kongclusterplugin_types.go
+++ b/railgun/apis/configuration/v1/kongclusterplugin_types.go
@@ -22,6 +22,7 @@ import (
 )
 
 //+genclient
+//+genclient:nonNamespaced
 //+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
 //+kubebuilder:object:root=true
 //+kubebuilder:subresource:status
```

@tharun208 if you add that tag and then run `make generate.clientsets` again it will properly add the updated clientset code.

**Comment by tharun208** [comment]
https://stupefied-goodall-e282f7.netlify.app/contributors/devel/generating-clientset/ This document says we need to tag a separate tag for cluster scoped crd generation.

**Comment by tharun208** [comment]
and also the makefile is not having a command to install the `client-gen` tool. will try to add it in a separate PR.

**Comment by rainest** [comment]
There are two outstanding issues. One is that I forgot the ingress class annotation on my original test object. That's easy to fix:

```
diff --git a/railgun/test/integration/plugin_test.go b/railgun/test/integration/plugin_test.go
index b439d77b..482774b4 100644
--- a/railgun/test/integration/plugin_test.go
+++ b/railgun/test/integration/plugin_test.go
@@ -95,6 +95,9 @@ func TestMinimalPlugin(t *testing.T) {
        kongclusterplugin := &kongv1.KongClusterPlugin{
                ObjectMeta: metav1.ObjectMeta{
                        Name: "legal",
+                       Annotations: map[string]string{
+                               annotations.IngressClassKey: ingressClass,
+                       },
                },
                PluginName: "request-termination",
                Config: apiextensionsv1.JSON{
```

The second part is weirder. For some reason the store isn't being constructed correctly:

```
> github.com/kong/kubernetes-ingress-controller/pkg/store.Store.GetKongClusterPlugin() /tmp/ingress-controller/pkg/store/store.go:483 (PC: 0x12d8746)
   478:		return p.(*kongv1.KongPlugin), nil
   479:	}
   480:	
   481:	// GetKongClusterPlugin returns the 'name' KongClusterPlugin resource.
   482:	func (s Store) GetKongClusterPlugin(name string) (*kongv1.KongClusterPlugin, error) {
=> 483:		p, exists, err := s.stores.ClusterPlugin.GetByKey(name)
   484:		if err != nil {
   485:			return nil, err
   486:		}
   487:		if !exists {
   488:			return nil, ErrNotFound{fmt.Sprintf("KongClusterPlugin %v not found", name)}

(dlv) p s.stores.ClusterPlugin.cacheStorage.items
map[string]interface {} [
	"/legal": *github.com/kong/kubernetes-ingress-controller/railgun/apis/configuration/v1.KongClusterPlugin {
		TypeMeta: (*"k8s.io/apimachinery/pkg/apis/meta/v1.TypeMeta")(0xc0004b7800),
		ObjectMeta: (*"k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta")(0xc0004b7820),
		ConsumerRef: "",
		Disabled: false,
		Config: (*"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1.JSON")(0xc0004b7930),
		ConfigFrom: (*"github.com/kong/kubernetes-ingress-controller/railgun/apis/configuration/v1.NamespacedConfigSource")(0xc0004b7948),
		PluginName: "request-termination",
		RunOn: "",
		Protocols: []string len: 0, cap: 0, nil,}, 
]

(dlv) call s.stores.ClusterPlugin.GetByKey("/legal")
> github.com/kong/kubernetes-ingress-controller/pkg/store.Store.GetKongClusterPlugin() /tmp/ingress-controller/pkg/store/store.go:483 (PC: 0x12d8746)
Values returned:
	item: interface {}(*github.com/kong/kubernetes-ingress-controller/railgun/apis/configuration/v1.KongClusterPlugin) *{
		TypeMeta: k8s.io/apimachinery/pkg/apis/meta/v1.TypeMeta {
			Kind: "KongClusterPlugin",
			APIVersion: "configuration.konghq.com/v1",},
		ObjectMeta: k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta {
			Name: "legal",
```

Looks like wherever we insert this into the store is still treating this like a namespaced object (a KongPlugin would have a key like `namespace/name`, but since there's no actual namespace, it just gets the empty string before the slash. Need to track down where that gets inserted so we can prune the slash.

**Comment by rainest** [comment]
Alright, looks like the second part is simple if more annoying to track down:

```
 // NewCacheStores is a convenience function for CacheStores to initialize all attributes with new cache stores
 func NewCacheStores() (c CacheStores) {
-       c.ClusterPlugin = cache.NewStore(keyFunc)
+       c.ClusterPlugin = cache.NewStore(clusterResourceKeyFunc)
```

This was [new for 2.x only](https://github.com/Kong/kubernetes-ingress-controller/pull/1163/files#diff-fb9f8e8a65e63ef4cf1e15404b8bc0aa9d3694209d9ba484984f6a78f2207b64R129). Not entirely sure how 1.x store worked. Apparently it just uses the stuff in fake_store.go (which had the correct key function)? Not worth investigating too much.

@tharun208 with [cluster.diff.txt](https://github.com/Kong/kubernetes-ingress-controller/files/6640800/cluster.diff.txt) on top of the previous commits here tests will pass. You'll want to pull the latest upstream copy of next and rebase to that also.

**Review by rainest — APPROVED** [review]

**Pull request merged**
