### PR TITLE
prepare release 2.10.2

### LINKED ISSUE #4263: release 2.10.2
### Release Type

patch

### **For all releases** Github Workflow Test Matrix Checkup

- [x] Check the testing workflow ([.github/workflows/_integration_tests.yaml](/Kong/kubernetes-ingress-controller/blob/main/.github/workflows/_integration_tests.yaml)) and ensure that all matrix versions ([.github/workflows/_e2e_tests.yaml](/Kong/kubernetes-ingress-controller/blob/main/.github/workflows/_e2e_tests.yaml) (for both K8s and Istio with K8s matrix) and [.github/workflows/release.yaml](/Kong/kubernetes-ingress-controller/blob/main/.github/workflows/release.yaml))  are up to date for various component releases. If there have been any new releases (major, minor or patch) of those components since the latest version seen in that configuration make sure the new versions get added before proceeding with the release. Remove any versions that are no longer supported by the environment provider.
- [x] Kubernetes (via [KIND](https://hub.docker.com/r/kindest/node/tags) and the latest image available when creating a new rapid channel cluster from the GKE new cluster wizard)
- [x] Istio (via [Istio's releases page](https://istio.io/latest/news/releases))

### Bump Kong Gateway version in manifests

- [x] Note: it might be possible that the latest Gateway version is not compatible with KIC and code changes are required. In such case, a decision whether to release with no compliance with the latest Gateway version should be made on a team level.
- [x] Check the latest minor Kong Gateway release in [Kong releases](https://github.com/Kong/kong/releases).
- [ ] Make sure the image tag in [config/image/enterprise/kustomization.yaml](/Kong/kubernetes-ingress-controller/blob/main/config/image/enterprise/kustomization.yaml) and [config/image/oss/kustomization.yaml](/Kong/kubernetes-ingress-controller/blob/main/config/image/oss/kustomization.yaml) is updated accordingly.
- [x] Run `make manifests` to regenerate manifests using the modified kustomizations and open a PR with the changes (similarly to [this PR](https://github.com/Kong/kubernetes-ingress-controller/pull/3288)).

### **For major/minor releases** Create `release/<MAJOR>.<MINOR>.x` Branch

- [ ] Create the `release/<MAJOR>.<MINOR>.x` branch at the place where you want to branch of off main

### **For all releases** Create `prepare-release/x.y.z` Branch

- [x] Ensure that you have up to date copy of `main`: `git checkout main; git pull` or a targeted release branch e.g. `release/2.7.x`: `git checkout release/2.7.x; git pull`
- [x] Create the `prepare-release` branch for the version (e.g. `prepare-release/2.7.1`): `git branch -m prepare-release/2.7.1`
- [x] Make any final adjustments to CHANGELOG.md. Double-check that dates are correct, that link anchors point to the correct header, and that you've included a link to the Github compare link at the end. If there were any RC releases before this version, fold their changes into the final release entry.
- [ ] Resolve all licensing issues that FOSSA has detected. Go to Issues tab in FOSSA's KIC project and resolve every issue, inspecting if it's a false positive or not. [ignored.go](https://github.com/Kong/team-k8s/blob/main/fossa/ignored.go) script should be useful to look for issues that have been already resolved and reappeared due to version changes.
- [ ] Update [ignored.json](https://github.com/Kong/team-k8s/blob/main/fossa/kubernetes-ingress-controller/ignored.json) following instructions in [README](https://github.com/Kong/team-k8s/blob/main/fossa/README.md).
- [ ] Retrieve the latest license report from FOSSA and save it to LICENSES (go to Reports tab in FOSSA's KIC project, select 'plain text' format, tick 'direct dependencies' and download it).
- [ ] Ensure base manifest versions use the new version (`config/image/enterprise/kustomization.yaml` and `config/image/oss/kustomization.yaml`) and update manifest files: `make manifests`
- [x] Push the branch up to the remote: `git push --set-upstream origin prepare-release/x.y.z`

### **For all releases** Create a Release Pull Request

- [ ] Check the [latest E2E nightly test run](https://github.com/Kong/kubernetes-ingress-controller/actions/workflows/e2e_nightly.yaml) to confirm that E2E tests are succeeding. If you are backporting features into a non-main branch, run a [targeted E2E job against that branch](https://github.com/Kong/kubernetes-ingress-controller/actions/workflows/e2e_targeted.yaml) or use `ci/run-e2e` label on the PR preparing the release.
- [x] Open a PR from your branch to `main`. Set a `backport release/X.Y.Z` label.
- [x] If this is a patch release, ensure that the release branch (e.g. `release/2.9.x`) compared against the latest patch for this minor release (e.g. `v2.9.0`) includes the expected changes that the release should include (e.g. by checking [https://github.com/kong/kubernetes-ingress-controller/compare/v2.9.0..release/2.9.x](https://github.com/kong/kubernetes-ingress-controller/compare/v2.9.0..release/2.9.x)).
- [ ] Once the PR is merged (the `prepare-release/x.y.z` branch will get automatically removed), approve and merge the automatic backport PR and [initiate a release job](https://github.com/Kong/kubernetes-ingress-controller/actions/workflows/release.yaml) on the release branch. Your tag must use `vX.Y.Z` format. Set `latest` to true if this will be the latest release.
- [ ] CI will validate the requested version, build and push an image, and run tests against the image before finally creating a tag and publishing a release. If tests fail, CI will push the image but not the tag or release. Investigate the failure, correct it as needed, and start a new release job.

### **For major/minor releases only** Update Release documents

- [ ] Trigger [release_docs](https://github.com/Kong/kubernetes-ingress-controller/blob/main/.github/workflows/release_docs.yaml) workflow. Note that you will need to update the new version's navigation manifest (e.g. [for 2.7](https://github.com/Kong/docs.konghq.com/blob/main/app/_data/docs_nav_kic_2.7.x.yml) to use the new file after.
- [ ] Ensure a draft PR is created in [docs.konghq.com](https://github.com/Kong/docs.konghq.com/pulls) repository.
- [ ] Update articles in the new version as needed.
- [ ] Update `references/version-compatibility.md` to include the new versions (make sure you capture any new Kubernetes/Istio versions that have been tested)
- [ ] Copy `app/_data/docs_nav_kic_OLDVERSION.yml` to `app/_data/docs_nav_kic_NEWVERSION.yml` and update the `release` field to `NEWVERSION`. Add entries for any new articles.
- [ ] Make sure that `app/_data/docs_nav_kic_NEWVERSION.yml` links to the latest generated `custom-resources-X.X.X.md`.
- [ ] Add a section to `app/_data/kong_versions.yml` for your version.
- [ ] Add entries in support policy documents: `app/_includes/md/support-policy.md` and `app/_src/kubernetes-ingress-controller/support-policy.md`.
- [ ] Mark the PR ready for review.
- [ ] Inform and ping the @team-k8s via slack of impending release with a link to the release PR.

### Release Troubleshooting

The [Release Troubleshooting guide](https://github.com/Kong/kubernetes-ingress-controller/blob/main/RELEASE.md#release-troubleshooting) covers strategies for dealing with a release that has failed.

### PR DESCRIPTION
**Pull request by randmonkey**
**What this PR does / why we need it**:

prepare release 2.10.2

**Which issue this PR fixes**:

fixes #4263 

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

**Review by pmalek — APPROVED** [review]

**Comment by pmalek** [comment]
We still have some e2e tests failing 😢 


[run / kind (1.24.15, TestDeployAllInOnePostgresWithMultipleReplicas$)](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/5472481042/jobs/9965520352#step:8:678)
[run / gke (v1.26.5, TestDeployAllInOneDBLESSNoLoadBalancer$)](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/5472481042/jobs/9965532018#step:5:545)
[run / gke (v1.26.5, TestDeployAllInOneDBLESSGateway$)](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/5472481042/jobs/9965531786#step:5:527)

**Comment by randmonkey** [comment]
> We still have some e2e tests failing cry
> 
> [run / kind (1.24.15, TestDeployAllInOnePostgresWithMultipleReplicas$)](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/5472481042/jobs/9965520352#step:8:678) [run / gke (v1.26.5, TestDeployAllInOneDBLESSNoLoadBalancer$)](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/5472481042/jobs/9965532018#step:5:545) [run / gke (v1.26.5, TestDeployAllInOneDBLESSGateway$)](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/5472481042/jobs/9965531786#step:5:527)

[run / kind (1.24.15, TestDeployAllInOnePostgresWithMultipleReplicas$)](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/5472481042/jobs/9965520352#step:8:678) This one succeeded after re-run.
The other two are both cases run on GKE and calls `verifyGateway`. According to the logs, the condition is already "Programmed", but the check did not pass:
https://github.com/Kong/kubernetes-ingress-controller/actions/runs/5472481042/jobs/9967086433
```
  helpers_gateway_test.go:95: conditions: [***Accepted Unknown 0 1970-01-01 00:00:00 +0000 UTC NotReconciled Waiting for controller***]
    helpers_gateway_test.go:95: conditions: [***Accepted Unknown 0 1970-01-01 00:00:00 +0000 UTC NotReconciled Waiting for controller***]
    helpers_gateway_test.go:95: conditions: [***Accepted Unknown 0 1970-01-01 00:00:00 +0000 UTC NotReconciled Waiting for controller***]
    helpers_gateway_test.go:95: conditions: [***Accepted True 1 2023-07-06 09:04:28 +0000 UTC Accepted this unmanaged gateway has been picked up by the controller and will be processed*** ***Programmed True 1 2023-07-06 09:04:28 +0000 UTC Programmed ***]
    helpers_gateway_test.go:95: conditions: [***Accepted True 1 2023-07-06 09:04:28 +0000 UTC Accepted this unmanaged gateway has been picked up by the controller and will be processed*** ***Programmed True 1 2023-07-06 09:04:28 +0000 UTC Programmed ***]
    helpers_gateway_test.go:95: conditions: [***Accepted True 1 2023-07-06 09:04:28 +0000 UTC Accepted this unmanaged gateway has been picked up by the controller and will be processed*** ***Programmed True 1 2023-07-06 09:04:28 +0000 UTC Programmed ***]
    helpers_gateway_test.go:95: conditions: [***Accepted True 1 2023-07-06 09:04:28 +0000 UTC Accepted this unmanaged gateway has been picked up by the controller and will be processed*** ***Programmed True 1 2023-07-06 09:04:28 +0000 UTC Programmed ***]
    helpers_gateway_test.go:95: conditions: [***Accepted True 1 2023-07-06 09:04:28 +0000 UTC Accepted this unmanaged gateway has been picked up by the controller and will be processed*** ***Programmed True 1 2023-07-06 09:04:28 +0000 UTC Programmed ***]
    helpers_gateway_test.go:95: conditions: [***Accepted True 1 2023-07-06 09:04:28 +0000 UTC Accepted this unmanaged gateway has been picked up by the controller and will be processed*** ***Programmed True 1 2023-07-06 09:04:28 +0000 UTC Programmed ***]
    helpers_gateway_test.go:95: conditions: [***Accepted True 1 2023-07-06 09:04:28 +0000 UTC Accepted this unmanaged gateway has been picked up by the controller and will be processed*** ***Programmed True 1 2023-07-06 09:04:28 +0000 UTC Programmed ***]
    helpers_gateway_test.go:95: conditions: [***Accepted True 1 2023-07-06 09:04:28 +0000 UTC Accepted this unmanaged gateway has been picked up by the controller and will be processed*** ***Programmed True 1 2023-07-06 09:04:28 +0000 UTC Programmed ***]
    helpers_gateway_test.go:95: conditions: [***Accepted True 1 2023-07-06 09:04:28 +0000 UTC Accepted this unmanaged gateway has been picked up by the controller and will be processed*** ***Programmed True 1 2023-07-06 09:04:28 +0000 UTC Programmed ***]
...
   helpers_gateway_test.go:82: 
        	Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/e2e/helpers_gateway_test.go:82
        	            				/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/e2e/features_test.go:474
        	Error:      	Condition never satisfied
        	Test:       	TestDeployAllInOneDBLESSNoLoadBalancer
```
Also, these are the only 2 cases calling `verifyGateway`. So there might be some problem in this check on GKE env. I suspect that the `Generation` field got from GKE may be wrong.

**Comment by czeslavo** [comment]
> Also, these are the only 2 cases calling verifyGateway. So there might be some problem in this check on GKE env. I suspect that the Generation field got from GKE may be wrong.

As I can see `verifyGateway` expects `Ready` condition to be `True` while there's no such condition set. 🤔

**Comment by czeslavo** [comment]
Ah, I just realized that the GKE tests are run with the nightly image from main, so there's not much value in running them on the release branch 🙄

**Comment by randmonkey** [comment]
> Ah, I just realized that the GKE tests are run with the nightly image from main, so there's not much value in running them on the release branch roll_eyes

Will GKE tests only run with `nightly` image? If so, it should run for only major/minor release.

**Comment by czeslavo** [comment]
> Will GKE tests only run with nightly image? If so, it should run for only major/minor release.

Yes, https://github.com/Kong/kubernetes-ingress-controller/pull/4287 backport makes them to be not run in the targeted workflow.

**Pull request merged**
