### PR TITLE
[KEP] 0007-performance-test 

### PR DESCRIPTION
**Pull request by ccfishk**
---
status: provisional
---
# Kubernetes Ingress Controller (KIC) Performance Testing

- [Summary](#summary)
- [Motivation](#motivation)
  - [Goals](#goals)
  - [Non-Goals](#non-goals)
- [Proposal](#proposal)
  - [User Stories](#user-stories)
    - [Story 1](#story-1)
    - [Story 2](#story-2)

### Goals
# Non Goals
## Proposal

### CODE REVIEW

**Comment by ccfishk** [comment]
revert to draft since is just a holder for document the idea.

**Comment by shaneutt** [comment]
should we close this now that https://github.com/Kong/kubernetes-ingress-controller/pull/1488 exists? It seems like we're not going to write a KEP anymore, instead we have the tests and some follow up issues which will suffice?

**Comment by ccfishk** [comment]
> should we close this now that #1488 exists? It seems like we're not going to write a KEP anymore, instead we have the tests and some follow up issues which will suffice?
> 


We did discussion, documentation and scope on https://github.com/Kong/kubernetes-ingress-controller/issues/1197. https://github.com/Kong/kubernetes-ingress-controller/pull/1488 is follow up concrete implementation.

**Comment by ccfishk** [comment]
The actual KEP work is documented in #1197

**Pull request closed without merging**
