### PR TITLE
 chore: simplify tools installation and management with mise

### PR DESCRIPTION
**Pull request by programmer04**
**What this PR does / why we need it**:

> 🙇 Please test locally on your machine.

> ❗ There is a problem with `Checks / linters / lint (pull_request_target)`, because we use workflow from `main` branch and it uses `third_party/go.mod` that is removed in this file, so it has to be merged with by-passing and observing on `main`

Scope 
- Get rid of dir `third_party` and dedicated `go.mod` for managing tooling and all related `Makefile` config. Use `mise` to install [delve](https://github.com/go-delve/delve) from the source code (a binary is not provided).
- `gotestsum` is handled natively
- `crd-ref-docs` use the same approach for installation as for `delve` - built from source
- `setup-envtest` is handled natively
- `staticcheck` is handled natively
- cleanup leftovers from already removed (see #6563) deprecated `looppointer` linter.

**Which issue this PR fixes**:

Follow up for https://github.com/Kong/kubernetes-ingress-controller/pull/6563

### CODE REVIEW

**Review by czeslavo — COMMENTED** [review]
Let's add the experimental setting to the `.mise.toml` config file so we don't have to set it manually:

```toml
[settings]
experimental = true
```

**Comment by programmer04** [comment]
I implemented your suggestion @czeslavo and made couple of other improvements, so please check everything again

**Review by pmalek — APPROVED** [review]
Looks good, worked on my machine 🎉

**Review by czeslavo — APPROVED** [review]
🚀

**Pull request merged**
