### PR TITLE
[feat] Support endpoint slices

### LINKED ISSUE #1172: Support EndpointSlice
In Kubernetes 1.21 ([release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md#v1210), [KEP](https://github.com/freehan/enhancements/blob/master/keps/sig-network/20190603-EndpointSlice-API.md)), `EndpointSlice` graduated to GA (GV: `discovery.k8s.io/v1`), as a replacement for `core/v1` `Endpoint`.

This means that KIC can use the following APIs to watch service endpoints:
- `core/v1` `Endpoint`: all versions, with limitations, likely deprecated in the future
- `discovery.k8s.io/v1beta1`: k8s 1.18-1.24 (in 1.17 behind a feature gate)
- `discovery.k8s.io/v1`: k8s 1.21+

### PR DESCRIPTION
**Pull request by scottd018**
**What this PR does / why we need it**:

Fixes #1172 to address endpoint slices in Kubernetes.

**Which issue this PR fixes**: 

fixes #1172, adds endpoint slices as an optional configuration when starting the controllers.

**Special notes for your reviewer**:

Support endpoint slices

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ x ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

**Comment by scottd018** [comment]
@mflendrich I have a decent start to add endpoint slices, before a final refactor.  I'm having some problems running integration tests in my environment, however I suspect the issue to be environmental.  Was hoping I can let the pipeline take care of this check as to save some time in troubleshooting, however it looks as if I need to have the workflow manually kicked off because I am a first time contributor.

Are you able to help here?  Thanks!

**Comment by mflendrich** [comment]
> Are you able to help here?  Thanks!

Done 👍

Feel free to file a bug whenever you think that the test does not work in your environment - maybe that's something we can (or even should) fix.

**Comment by scottd018** [comment]
> > Are you able to help here?  Thanks!
> 
> Done 👍
> 
> Feel free to file a bug whenever you think that the test does not work in your environment - maybe that's something we can (or even should) fix.

Thanks @mflendrich !  Looks like the integration test did run and pass (without the new endpoint slice logic), so I think this is probably something specific to my environment.  I've pushed up the new integration test.  If you can, kick it off again and in the meantime I can see about filing an issue for user-specific environments and push that up as well.

**Comment by mflendrich** [comment]
@scottd018 kicked off again. There's a test failure - PTAL.

Let me know if I can do something to let you run the tests offline, to shorten the feedback loop for you.

**Comment by scottnetlab** [comment]
Thanks @mflendrich .  I think I should be good.  I haven't dug deep yet, but I think it's how MetalLB is being configured in the KIND cluster.  I'll file a bug and I think I should be good.  Thanks again!

**Comment by scottnetlab** [comment]
@mflendrich I was able to get the integration tests working.  I found out that there are problems with using MacOS with Docker and making local connections, which was causing issues, so I used a Linux VM instead.  I opened an issue with a suggestion based on past experience at https://github.com/Kong/kubernetes-ingress-controller/issues/1626 to take a look at.

If you are able to, go ahead and kick it off again in the pipeline.  I think the integration test should pass now.

I still have a couple of small refactors I want to look at as well before considering this "done".

**Comment by scottd018** [comment]
@mflendrich I was able to get the integration tests working.  I found out that there are problems with using MacOS with Docker and making local connections, which was causing issues, so I used a Linux VM instead.  I opened an issue with a suggestion based on past experience at https://github.com/Kong/kubernetes-ingress-controller/issues/1626 to take a look at.

If you are able to, go ahead and kick it off again in the pipeline.  I think the integration test should pass now.

I still have a couple of small refactors I want to look at as well before considering this "done".

**Comment by scottd018** [comment]
@mflendrich This is ready for code review.  Please let me know if there is anything you'd like a discussion or clarification on, or anything that you feel needs fixed.  Happy to push new commits to satisfy your requirements.

**Comment by mflendrich** [comment]
@scottd018 

GH has automatically closed this PR because we've deleted the `next` branch.

Could you please change the target branch of this PR from `next` to `main` and reopen it? :pray: Only the author can do it.
The closure of this PR is **NOT** because we don't want to merge this PR.

**Comment by scottnetlab** [comment]
@mflendrich requested a new PR #1678 for this.  Also refactored a bit to meet the changes in the main branch.

**Comment by scottd018** [comment]
@mflendrich requested a new PR #1678 for this. Also refactored a bit to meet the changes in the main branch.

**Pull request closed without merging**
