### PR TITLE
chore(manifests): Bump kong to version 2.3 :tea:

### LINKED ISSUE #1041: Bump Kong to 2.3 in deploy manifests

### PR DESCRIPTION
**Pull request by mrnonz**
This is a new release of Kong, with no breaking changes with respect to the 2.x series.

[edit @mflendrich] fixes #1041

### CODE REVIEW

**Comment by mflendrich** [comment]
fixes #1041

**Review by mflendrich — CHANGES_REQUESTED** [review]
Thanks @mrnonz for your contribution.

KIC maintainers have made a choice to reference Kong images by `major.minor` tags instead of `major.minor.patch`, so that users get the latest patch version by default.

Therefore, please change `2.3.2` to `2.3` in all these places. This will pull the latest `2.3.x` version available :+1:.

**Comment by mflendrich** [comment]
@Kong/team-k8s **DO NOT MERGE** until the blocker on #1041 gets resolved.

**Comment by mrnonz** [comment]
> Thanks @mrnonz for your contribution.
> 
> KIC maintainers have made a choice to reference Kong images by `major.minor` tags instead of `major.minor.patch`, so that users get the latest patch version by default.
> 
> Therefore, please change `2.3.2` to `2.3` in all these places. This will pull the latest `2.3.x` version available 👍.

Hi, I have already update to `2.3` instead.

**Review by mflendrich — APPROVED** [review]
2.3 introduced a very restrictive version number check for hybrid mode that's being relaxed in 2.4: https://github.com/Kong/kong/pull/6932

Merging this PR nonetheless. Thanks for your contribution!

**Pull request merged**
