### PR TITLE
 chore(tests): migrate TestTCPIngressEssentials to isolated

### PR DESCRIPTION
**Pull request by LindaSummer**
**What this PR does / why we need it**:

Migrate test integration `TestTCPIngressEssentials` to isolated. Avoiding locking a port cuts execution time.

**Which issue this PR fixes**:

#5757

### CODE REVIEW

**Comment by LindaSummer** [comment]
Hi @programmer04 ,

Sorry to bother you.
I find the check failed in `Kong/kong-license` step.
It looks like missing some environment variables.
I have no idea on this failure. Secrets should be maintained by repo's configurations.
Could you help me and take a look? 😊

Best Regards,
Edward

**Comment by LindaSummer** [comment]
Hi @programmer04 ,

I enabled GitHub Actions in my fork repo for testing.
Maybe this effect the runner here?
I have disabled my fork repo's GitHub Actions.

Best Regards,
Edward

**Review by programmer04 — APPROVED** [review]

**Comment by programmer04** [comment]
Hey, @LindaSummer please rebase your PR on the newest `main` branch, the changes should allow run all of the checks on your PR (I will just have to retrigger the failing one), let's see

**Comment by LindaSummer** [comment]
> Hey, @LindaSummer please rebase your PR on the newest `main` branch, the changes should allow run all of the checks on your PR (I will just have to retrigger the failing one), let's see

Hi @programmer04 ,

Thanks very much for your warm help and patience! 😊
I have rebased on the latest main branch.

Best Regards,
Edward

**Comment by LindaSummer** [comment]
> Thank you @LindaSummer for your great contribution and cooperation!

Hi @programmer04 ,

Thanks very much for your patience and help! 😊

During my refactoring, I find that `tcproute_test.go` and `udproute_test.go` have some unit tests using the `tcpMutex` and `tlsMutex`.
Do they need to be migrated to isolated too?
If they need to be refactored, I'm very happy to make more contributions. 😊

Best Regards,
Edward

**Comment by programmer04** [comment]
Basically, we want to migrate all of our integration tests to isolated ones at some point. Issue mentions only those that use mutex, because they increase the time needed to run the suite. So any more contributions are more than welcome

**Pull request merged**
