### PR TITLE
request response buffering options

### LINKED ISSUE #924: Support Kong 2.2 request/response route buffering
[Kong 2.2](https://discuss.konghq.com/t/kong-2-2-0-beta-1-available/7232) introduces new boolean route configuration options, `request_buffering` and `response_buffering`. Both default to `true`.

KIC will need to support these via new annotations and KongIngress route configuration options.

### PR DESCRIPTION
**Pull request by shaneutt**
**What this PR does / why we need it**:
Add options to `KongIngress` and ingress annotations for `request_buffering` and `response_buffering` options.

**Which issue this PR fixes**
fixes #924

### CODE REVIEW

**Review by rainest — CHANGES_REQUESTED** [review]
Another case like https://github.com/Kong/kubernetes-ingress-controller/blob/1.1.0/internal/ingress/controller/parser/kongstate/route_test.go#L175-L192 (items are original route, KongIngress, expected route after override) will handle testing the new KongIngress logic. Otherwise LGTM

**Review by rainest — APPROVED** [review]

**Review by rainest — APPROVED** [review]

**Comment by hbagdi** [comment]
@Kong/team-k8s This actually wouldn't work in traditional/hybrid mode of kong: https://github.com/Kong/deck/issues/260
Can we start tracking this again?

**Comment by shaneutt** [comment]
> @Kong/team-k8s This actually wouldn't work in traditional/hybrid mode of kong: [Kong/deck#260](https://github.com/Kong/deck/issues/260)
> Can we start tracking this again?

I've assigned that one to me and I'll dig in.

**Comment by sahil-sharma** [comment]
@shaneutt Is there any update on this as I am facing the same issue?
image
I am having versions as mentioned below:
```
Kong version: 2.5.0-ubuntu (docker image)
Kong-Ingress-Controller: 1.3.2
Host OS: Ubuntu-20.04
K8s version: v1.20.1
```
I have installed a custom plugin (to my Kong docker image) that injects a Cookie response header to the client in every response (on a specific route).
I am able to receive a response back with HTTP 20X but there is no such header to the client while I added a Correlation-ID plugin and that I am able to get.
There is no error in `Kong-Ingress-Controller` Pod but, in `Kong-Proxy` pod I am seeing the above error.
Any hints on what kind of annotations I should add to Kong to enable response buffering.

**Comment by shaneutt** [comment]
> @shaneutt Is there any update on this as I am facing the same issue?
> image
> I am having versions as mentioned below:
> 
> ```
> Kong version: 2.5.0-ubuntu (docker image)
> Kong-Ingress-Controller: 1.3.2
> Host OS: Ubuntu-20.04
> K8s version: v1.20.1
> ```
> 
> I have installed a custom plugin (to my Kong docker image) that injects a Cookie response header to the client in every response (on a specific route).
> I am able to receive a response back with HTTP 20X but there is no such header to the client while I added a Correlation-ID plugin and that I am able to get.
> There is no error in `Kong-Ingress-Controller` Pod but, in `Kong-Proxy` pod I am seeing the above error.
> Any hints on what kind of annotations I should add to Kong to enable response buffering.

If you use the annotation route (rather than the CRD) then the annotations should be `konghq.com/request-buffering` and `konghq.com/response-buffering`.

The output you showed above is coming from the Kong Proxy (e.g. https://github.com/kong/kong as opposed to this ingress controller) on this line:

https://github.com/Kong/kong/blob/master/kong/init.lua#L840

This is telling you that v2 HTTP requests are involved, but not compatible with this feature.

As per the original PR for `request_buffering`:

https://github.com/Kong/kong/pull/6057

This is specific to HTTP v1.1 chunked encoding.

Going forward I don't think communicating via the comments in this old PR is ideal: If you need further guidance on this I would recommend opening a discussion thread for assistance either in `kong/kong`, or here in `kong/kubernetes-ingress-controller` depending on which component you feel you specifically need help with:

- https://github.com/kong/kong/discussions
- https://github.com/kong/kubernetes-ingress-controller/discussions

Let me know if the information above is helpful to you, and do feel free to open a thread if you need further assistance.

**Comment by sahil-sharma** [comment]
@shaneutt Make sense. Thanks for the inputs. I will open a new thread `kong/kong`. :pray:

**Comment by shaneutt** [comment]
> @shaneutt Make sense. Thanks for the inputs. I will open a new thread `kong/kong`. pray

Sounds good. If you end up needing any help with the Kubernetes components too let us know :vulcan_salute:

**Comment by sahil-sharma** [comment]
Thanks for this nice gesture, @shaneutt. :pray: 
BTW, I have created a discussion [thread](https://github.com/Kong/kong/discussions/7841).

**Pull request merged**
