### PR TITLE
chore(ci): remove redundant ${{ ... }} in if statements in workflows

### PR DESCRIPTION
**Pull request by programmer04**
**What this PR does / why we need it**:

When you use expressions in an if conditional, you may omit the `${{ ... }}` expression syntax because GitHub Actions automatically evaluates the `if` conditional as an expression. [Read more](https://docs.github.com/en/actions/learn-github-actions/expressions#about-expressions). I found a corner case where such omit is not applicable, e.g.

https://github.com/Kong/kubernetes-ingress-controller/blob/b6770b6dc5d90ece16d83baf58a04bdc95da3723/.github/workflows/_e2e_tests.yaml#L81

read more [here](https://github.com/orgs/community/discussions/26303#discussioncomment-6739171). 

Issue created in GH docs https://github.com/github/docs/pull/27497

### CODE REVIEW

**Review by randmonkey — COMMENTED** [review]
Are all the remaining `${{ }}` s are necessary?

**Comment by programmer04** [comment]
I think so @randmonkey only in `if` statements (with a caveat) they can be omitted

**Comment by pmalek** [comment]
@programmer04 Are we still working on this 🤔 ?

**Comment by programmer04** [comment]
Since omitting doesn't work always ([see official docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif)) I'm not longer advocating for adjusting it

**Pull request closed without merging**
