### PR TITLE
Update GWAPI to 0.8.0

### PR DESCRIPTION
**Pull request by rainest**
**What this PR does / why we need it**:

Updates the GWAPI version.

Adds a comment to a generator.

**Special notes for your reviewer**:

Currently an RC to test if conformance broke.

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

**Comment by mlavacca** [comment]
Fixes #4560

**Comment by mlavacca** [comment]
The conformance test failure related to the `AttachedRoutes` is tracked in #4546

**Comment by mlavacca** [comment]
The conformance test failure related to the `TLSRoute` invalid `ReferenceGrant` is tracked in #4562. We can disable such a test as it has been introduced recently and we are not conformant yet with `TLSRoute`s.

**Comment by rainest** [comment]
The final version requires fixes in main for new client-go compatibility, and rebasing with mod changes is annoying, so continuing in a new branch: https://github.com/Kong/kubernetes-ingress-controller/pull/4591

**Pull request closed without merging**
